import type pg from "pg";
import {mapProductSet,type ShopifyProductContext}from"./product-mapper.js";
export type ShopifyJob=Readonly<{id:string;revisionId:string;workspaceId:string;attempt:number}>;
type PayloadRow={content_data:Record<string,unknown>;brand_name:string;product_type:string;recommended_retail_minor:string;currency:string;external_product_id:string;snapshot_data:Record<string,unknown>;mockup_data:Record<string,unknown>|null};
export class ShopifyJobStore{
constructor(private readonly pool:pg.Pool){}
async claim(workerId:string,lease:number,max:number):Promise<ShopifyJob|null>{const q=await this.pool.query<{id:string;content_revision_id:string;workspace_id:string;attempts:number}>(`WITH n AS(SELECT id FROM shopify_publication_jobs WHERE(status='PENDING' AND attempts<$3 AND available_at<=now())OR(status='RUNNING' AND attempts<=$3 AND lease_expires_at<=now())ORDER BY available_at,created_at FOR UPDATE SKIP LOCKED LIMIT 1)UPDATE shopify_publication_jobs j SET status='RUNNING',attempts=attempts+1,locked_by=$1,lease_expires_at=now()+make_interval(secs=>$2),last_error=CASE WHEN j.status='RUNNING'THEN'LEASE_EXPIRED'ELSE j.last_error END FROM n WHERE j.id=n.id RETURNING j.id,j.content_revision_id,j.workspace_id,j.attempts`,[workerId,lease,max]);const r=q.rows[0];return r?{id:r.id,revisionId:r.content_revision_id,workspaceId:r.workspace_id,attempt:r.attempts}:null;}
async payload(job:ShopifyJob){const q=await this.pool.query<PayloadRow>(`SELECT r.content_data,bpr.profile_data->>'brand_name' brand_name,c.product_type,c.recommended_retail_minor,c.currency,c.external_product_id,cs.data snapshot_data,ms.data mockup_data FROM product_content_revisions r JOIN product_contents pc ON pc.id=r.product_content_id JOIN product_candidates c ON c.id=pc.candidate_id JOIN product_candidate_jobs cj ON cj.id=c.job_id JOIN brand_profile_revisions bpr ON bpr.id=cj.revision_id JOIN catalog_snapshots cs ON cs.id=c.catalog_snapshot_id JOIN shopify_publication_jobs spj ON spj.content_revision_id=r.id LEFT JOIN mockup_snapshots ms ON ms.id=spj.mockup_snapshot_id WHERE r.id=$1 AND r.status='APPROVED'`,[job.revisionId]);const r=q.rows[0];if(!r)throw Object.assign(new Error('Approved content revision not found'),{status:422});const products=Array.isArray(r.snapshot_data.products)?r.snapshot_data.products:[];const product=products.find(v=>v&&typeof v==='object'&&String((v as Record<string,unknown>).externalProductId)===r.external_product_id)as Record<string,unknown>|undefined;let variants=Array.isArray(product?.catalogVariants)?product.catalogVariants as NonNullable<ShopifyProductContext['variants']>:undefined;const images=Array.isArray(r.mockup_data?.images)?r.mockup_data.images as Record<string,unknown>[]:[];if(variants&&images.length){const urls=new Map(images.map(x=>[String(x.catalogVariantId),String(x.url)]));variants=variants.map(v=>({...v,imageUrl:urls.get(v.externalVariantId)??v.imageUrl}));}return mapProductSet({contentRevisionId:job.revisionId,content:r.content_data,brandName:r.brand_name,productType:r.product_type,retailMinor:Number(r.recommended_retail_minor),currency:r.currency,...(variants?{variants}:{})});}
async extend(id:string,w:string,l:number){const q=await this.pool.query("UPDATE shopify_publication_jobs SET lease_expires_at=now()+make_interval(secs=>$3) WHERE id=$1 AND status='RUNNING' AND locked_by=$2 AND lease_expires_at>now()",[id,w,l]);return q.rowCount===1;}
async success(id:string,w:string,payload:unknown,productId:string,raw:unknown){const q=await this.pool.query("UPDATE shopify_publication_jobs SET status='SUCCEEDED',finished_at=now(),locked_by=NULL,lease_expires_at=NULL,shopify_product_id=$3,request_payload=$4::jsonb,response_payload=$5::jsonb WHERE id=$1 AND status='RUNNING' AND locked_by=$2",[id,w,productId,JSON.stringify(payload),JSON.stringify(raw)]);return q.rowCount===1;}
async retry(id:string,w:string,code:string,delay:number){const q=await this.pool.query("UPDATE shopify_publication_jobs SET status='PENDING',available_at=now()+make_interval(secs=>$4/1000.0),last_error=$3,locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND status='RUNNING' AND locked_by=$2",[id,w,code,delay]);return q.rowCount===1;}
async deferConnection(id:string,w:string,delay=30_000){const q=await this.pool.query("UPDATE shopify_publication_jobs SET status='PENDING',attempts=GREATEST(0,attempts-1),available_at=now()+make_interval(secs=>$3/1000.0),last_error='WAITING_FOR_SHOPIFY_CONNECTION',locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND status='RUNNING' AND locked_by=$2",[id,w,delay]);return q.rowCount===1;}
async deferRateLimit(id:string,w:string,delay:number){const q=await this.pool.query("UPDATE shopify_publication_jobs SET status='PENDING',attempts=GREATEST(0,attempts-1),available_at=now()+make_interval(secs=>$3/1000.0),last_error='WAITING_FOR_SHOPIFY_RATE_LIMIT',locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND status='RUNNING' AND locked_by=$2",[id,w,delay]);return q.rowCount===1;}
async fail(id:string,w:string,code:string){const q=await this.pool.query("UPDATE shopify_publication_jobs SET status='FAILED',finished_at=now(),last_error=$3,locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND status='RUNNING' AND locked_by=$2",[id,w,code]);return q.rowCount===1;}}
