import {createHmac} from "node:crypto";
import type pg from "pg";

export type PrivacyAlertPayload=Readonly<{id:string;level:string;requestType:string;shopDomain:string;dueAt:string;openedAt:string}>;
export type PrivacyMaintenanceAlertPayload=Readonly<{category:"PRIVACY_MAINTENANCE";id:string;incidentType:string;lastError:string|null;openedAt:string;updatedAt:string}>;
export interface PrivacyAlertSender{send(payload:PrivacyAlertPayload|PrivacyMaintenanceAlertPayload):Promise<{status:number}>}

export class SignedPrivacyAlertWebhook implements PrivacyAlertSender{
  private readonly url:URL;
  constructor(url:string,private readonly secret:string,private readonly fetcher:typeof fetch=fetch){this.url=new URL(url);if(this.url.protocol!=="https:")throw new Error("PRIVACY_ALERT_WEBHOOK_URL must use HTTPS");if(secret.length<16)throw new Error("PRIVACY_ALERT_WEBHOOK_SECRET must be at least 16 characters");}
  async send(payload:PrivacyAlertPayload){const body=JSON.stringify(payload),timestamp=Math.floor(Date.now()/1000).toString(),signature=createHmac("sha256",this.secret).update(timestamp+"."+body).digest("hex"),response=await this.fetcher(this.url,{method:"POST",headers:{"Content-Type":"application/json","X-Storzy-Timestamp":timestamp,"X-Storzy-Signature":"sha256="+signature},body,signal:AbortSignal.timeout(10_000)});if(!response.ok)throw Object.assign(new Error(`Alert webhook returned ${response.status}`),{status:response.status});return{status:response.status};}
}

type Claimed={id:string;alert_id:string;attempts:number;level:string;request_type:string;shop_domain:string;due_at:Date;opened_at:Date};
export class PrivacyAlertDeliveryService{
  constructor(private readonly pool:pg.Pool,private readonly sender:PrivacyAlertSender,private readonly options:{workerId:string;maxAttempts:number;leaseSeconds:number}={workerId:"privacy-alert-delivery",maxAttempts:6,leaseSeconds:30}){}
  async deliverBatch(limit=20){if(!Number.isInteger(limit)||limit<1||limit>100)throw new Error("limit must be between 1 and 100");await this.pool.query("UPDATE privacy_alert_deliveries SET status='FAILED',available_at=now(),locked_by=NULL,lease_expires_at=NULL,last_error=COALESCE(last_error,'DELIVERY_LEASE_EXPIRED') WHERE status='RUNNING' AND lease_expires_at<=now()");await this.pool.query(`INSERT INTO privacy_alert_deliveries(id,alert_id) SELECT gen_random_uuid(),a.id FROM privacy_sla_alerts a WHERE a.status IN('OPEN','ACKNOWLEDGED') ON CONFLICT(alert_id) DO NOTHING`);const claimed=await this.pool.query<Claimed>(`WITH candidates AS(SELECT d.id FROM privacy_alert_deliveries d JOIN privacy_sla_alerts a ON a.id=d.alert_id WHERE d.status IN('PENDING','FAILED') AND d.available_at<=now() AND d.attempts<$3 AND a.status IN('OPEN','ACKNOWLEDGED') ORDER BY d.available_at,d.created_at FOR UPDATE OF d SKIP LOCKED LIMIT $1),updated AS(UPDATE privacy_alert_deliveries d SET status='RUNNING',attempts=d.attempts+1,locked_by=$2,lease_expires_at=now()+($4::text||' seconds')::interval,last_error=NULL FROM candidates c WHERE d.id=c.id RETURNING d.id,d.alert_id,d.attempts) SELECT u.id,u.alert_id,u.attempts,a.level,r.request_type,r.shop_domain,a.due_at,a.opened_at FROM updated u JOIN privacy_sla_alerts a ON a.id=u.alert_id JOIN shopify_privacy_requests r ON r.id=a.request_id`,[limit,this.options.workerId,this.options.maxAttempts,this.options.leaseSeconds]);let sent=0,failed=0;for(const row of claimed.rows){const payload={id:row.alert_id,level:row.level,requestType:row.request_type,shopDomain:row.shop_domain,dueAt:row.due_at.toISOString(),openedAt:row.opened_at.toISOString()};try{const result=await this.sender.send(payload);await this.pool.query("UPDATE privacy_alert_deliveries SET status='SENT',response_status=$3,sent_at=now(),locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND locked_by=$2",[row.id,this.options.workerId,result.status]);sent++;}catch(error){const status=typeof(error as {status?:unknown}).status==="number"?(error as {status:number}).status:null,message=error instanceof Error?error.message:String(error),delay=Math.min(3600,30*2**Math.max(0,row.attempts-1));await this.pool.query("UPDATE privacy_alert_deliveries SET status='FAILED',response_status=$3,last_error=$4,available_at=now()+($5::text||' seconds')::interval,locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND locked_by=$2",[row.id,this.options.workerId,status,message.slice(0,1000),delay]);failed++;}}return{claimed:claimed.rows.length,sent,failed};}

  async deliverMaintenanceBatch(limit=20){
    if(!Number.isInteger(limit)||limit<1||limit>100)throw new Error("limit must be between 1 and 100");
    await this.pool.query("UPDATE privacy_maintenance_alert_deliveries SET status='FAILED',available_at=now(),locked_by=NULL,lease_expires_at=NULL,last_error=COALESCE(last_error,'DELIVERY_LEASE_EXPIRED') WHERE status='RUNNING' AND lease_expires_at<=now()");
    await this.pool.query(`INSERT INTO privacy_maintenance_alert_deliveries(id,incident_id,incident_opened_at) SELECT gen_random_uuid(),id,opened_at FROM privacy_maintenance_incidents WHERE status='OPEN' ON CONFLICT(incident_id,incident_opened_at) DO NOTHING`);
    const claimed=await this.pool.query<{id:string;incident_id:string;attempts:number;incident_type:string;last_error:string|null;opened_at:Date;updated_at:Date}>(`WITH candidates AS(SELECT d.id FROM privacy_maintenance_alert_deliveries d JOIN privacy_maintenance_incidents i ON i.id=d.incident_id AND i.opened_at=d.incident_opened_at WHERE d.status IN('PENDING','FAILED') AND d.available_at<=now() AND d.attempts<$3 AND i.status='OPEN' ORDER BY d.available_at,d.created_at FOR UPDATE OF d SKIP LOCKED LIMIT $1),updated AS(UPDATE privacy_maintenance_alert_deliveries d SET status='RUNNING',attempts=d.attempts+1,locked_by=$2,lease_expires_at=now()+($4::text||' seconds')::interval,last_error=NULL FROM candidates c WHERE d.id=c.id RETURNING d.id,d.incident_id,d.attempts,d.incident_opened_at) SELECT u.id,u.incident_id,u.attempts,i.incident_type,i.last_error,i.opened_at,i.updated_at FROM updated u JOIN privacy_maintenance_incidents i ON i.id=u.incident_id`,[limit,this.options.workerId,this.options.maxAttempts,this.options.leaseSeconds]);
    let sent=0,failed=0;
    for(const row of claimed.rows){const payload:PrivacyMaintenanceAlertPayload={category:"PRIVACY_MAINTENANCE",id:row.incident_id,incidentType:row.incident_type,lastError:row.last_error,openedAt:row.opened_at.toISOString(),updatedAt:row.updated_at.toISOString()};try{const result=await this.sender.send(payload);await this.pool.query("UPDATE privacy_maintenance_alert_deliveries SET status='SENT',response_status=$3,sent_at=now(),locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND locked_by=$2",[row.id,this.options.workerId,result.status]);sent++;}catch(error){const status=typeof(error as{status?:unknown}).status==="number"?(error as{status:number}).status:null,message=error instanceof Error?error.message:String(error),delay=Math.min(3600,30*2**Math.max(0,row.attempts-1));await this.pool.query("UPDATE privacy_maintenance_alert_deliveries SET status='FAILED',response_status=$3,last_error=$4,available_at=now()+($5::text||' seconds')::interval,locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND locked_by=$2",[row.id,this.options.workerId,status,message.slice(0,1000),delay]);failed++;}}
    return{claimed:claimed.rows.length,sent,failed};
  }
}
