import {createHash,randomUUID}from"node:crypto";import type pg from"pg";import type{MockupImage}from"./response.js";
import {assertMockupExecutionSafety}from"./execution-gate.js";
export type MockupJob=Readonly<{id:string;revisionId:string;assetId:string;workspaceId:string;remoteTaskIds:string[]|null;attempt:number}>;
export class MockupJobStore{constructor(private readonly pool:pg.Pool){}async claim(worker:string,lease=60,max=8):Promise<MockupJob|null>{const q=await this.pool.query<{id:string;content_revision_id:string;design_asset_id:string;workspace_id:string;remote_task_ids:string[]|null;attempts:number}>(`WITH n AS(SELECT id FROM printful_mockup_jobs WHERE ((status IN ('PENDING','WAITING_REMOTE') AND available_at<=now() AND attempts<$3) OR (status='RUNNING' AND lease_expires_at<=now() AND attempts<=$3)) ORDER BY available_at,created_at FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE printful_mockup_jobs j SET status='RUNNING',attempts=attempts+1,locked_by=$1,lease_expires_at=now()+make_interval(secs=>$2) FROM n WHERE j.id=n.id RETURNING j.id,j.content_revision_id,j.design_asset_id,j.workspace_id,j.remote_task_ids,j.attempts`,[worker,lease,max]);const r=q.rows[0];return r?{id:r.id,revisionId:r.content_revision_id,assetId:r.design_asset_id,workspaceId:r.workspace_id,remoteTaskIds:r.remote_task_ids,attempt:r.attempts}:null;}
async createPayload(job:MockupJob){const q=await this.pool.query<{external_product_id:string;snapshot_data:Record<string,unknown>;file_url:string;placement:string;technique:string;mockup_style_ids:number[];resolution_status:string;width_px:number|null;height_px:number|null;effective_dpi:string|null;print_guideline:unknown}>(`SELECT c.external_product_id,cs.data snapshot_data,da.file_url,da.placement,da.technique,da.mockup_style_ids,da.resolution_status,da.width_px,da.height_px,da.effective_dpi,da.print_guideline FROM design_assets da JOIN product_candidates c ON c.id=da.candidate_id JOIN catalog_snapshots cs ON cs.id=c.catalog_snapshot_id WHERE da.id=$1`,[job.assetId]);const r=q.rows[0];if(!r)throw new Error('Design asset context not found');assertMockupExecutionSafety({resolutionStatus:r.resolution_status,widthPx:r.width_px,heightPx:r.height_px,effectiveDpi:r.effective_dpi===null?null:Number(r.effective_dpi),placement:r.placement,technique:r.technique,mockupStyleIds:r.mockup_style_ids,printGuideline:r.print_guideline});const products=Array.isArray(r.snapshot_data.products)?r.snapshot_data.products:[];const p=products.find(x=>x&&typeof x==='object'&&String((x as Record<string,unknown>).externalProductId)===r.external_product_id)as Record<string,unknown>|undefined;const variants=Array.isArray(p?.catalogVariants)?p.catalogVariants as Record<string,unknown>[]:[];const ids=variants.map(v=>Number(v.externalVariantId)).filter(Number.isInteger);if(!ids.length)throw new Error('No eligible Printful variants');return{format:'jpg',mockup_width_px:1000,products:[{source:'catalog',catalog_product_id:Number(r.external_product_id),catalog_variant_ids:ids,mockup_style_ids:r.mockup_style_ids,placements:[{placement:r.placement,technique:r.technique,layers:[{type:'file',url:r.file_url}]}]}]};}
async waiting(id:string,worker:string,ids:string[],delayMs=10_000){await this.pool.query(`UPDATE printful_mockup_jobs SET status='WAITING_REMOTE',remote_task_ids=$3::jsonb,available_at=now()+make_interval(secs=>$4/1000.0),locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND locked_by=$2`,[id,worker,JSON.stringify(ids),delayMs]);}
async deferConnection(id:string,worker:string,delayMs=30_000){await this.pool.query(`UPDATE printful_mockup_jobs SET status='PENDING',attempts=GREATEST(0,attempts-1),last_error='WAITING_FOR_PRINTFUL_CONNECTION',available_at=now()+make_interval(secs=>$3/1000.0),locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND status='RUNNING' AND locked_by=$2`,[id,worker,delayMs]);}
async deferRateLimit(id:string,worker:string,delayMs:number){await this.pool.query(`UPDATE printful_mockup_jobs SET status=CASE WHEN remote_task_ids IS NULL THEN 'PENDING' ELSE 'WAITING_REMOTE' END,attempts=GREATEST(0,attempts-1),last_error='WAITING_FOR_PRINTFUL_RATE_LIMIT',available_at=now()+make_interval(secs=>$3/1000.0),locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND status='RUNNING' AND locked_by=$2`,[id,worker,delayMs]);}
async retry(job:MockupJob,worker:string,delayMs:number,error:string){await this.pool.query(`UPDATE printful_mockup_jobs SET status=CASE WHEN remote_task_ids IS NULL THEN 'PENDING' ELSE 'WAITING_REMOTE' END,last_error=$4,available_at=now()+make_interval(secs=>$3/1000.0),locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND status='RUNNING' AND locked_by=$2`,[job.id,worker,delayMs,error]);}
async complete(job:MockupJob,worker:string,images:readonly MockupImage[]){const data={images};const json=JSON.stringify(data);const snapshotId=randomUUID();const client=await this.pool.connect();try{await client.query('BEGIN');await client.query(`INSERT INTO mockup_snapshots(id,mockup_job_id,data,checksum,image_count) VALUES($1,$2,$3::jsonb,$4,$5)`,[snapshotId,job.id,json,createHash('sha256').update(json).digest('hex'),images.length]);await client.query(`UPDATE printful_mockup_jobs SET status='SUCCEEDED',finished_at=now(),locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND locked_by=$2`,[job.id,worker]);await client.query(`UPDATE shopify_publication_jobs SET status='PENDING',mockup_snapshot_id=$2,available_at=now() WHERE content_revision_id=$1 AND status='WAITING_FOR_MOCKUP'`,[job.revisionId,snapshotId]);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
async fail(id:string,worker:string,error:string){await this.pool.query(`UPDATE printful_mockup_jobs SET status='FAILED',last_error=$3,finished_at=now(),locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND locked_by=$2`,[id,worker,error]);}}
