import{describe,expect,it,vi}from"vitest";import{HttpDesignFileInspector}from"../src/mockups/file-inspector.js";
const publicDns=async()=>["203.0.113.10"];
const png=(width:number,height:number)=>{const bytes=new Uint8Array(24);bytes.set([137,80,78,71,13,10,26,10],0);bytes.set([73,72,68,82],12);new DataView(bytes.buffer).setUint32(16,width);new DataView(bytes.buffer).setUint32(20,height);return bytes};
describe("design file inspector",()=>{
  it("accepts a public PNG below the Printful limits",async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(png(4000,5000),{status:206,headers:{"content-type":"image/png","content-range":"bytes 0-23/1024"}}));await expect(new HttpDesignFileInspector(fetcher,publicDns).inspect("https://cdn.example/design.png")).resolves.toEqual({url:"https://cdn.example/design.png",mimeType:"image/png",sizeBytes:1024,widthPx:4000,heightPx:5000});expect(fetcher).toHaveBeenCalledWith(expect.any(URL),expect.objectContaining({redirect:"manual",headers:{Range:"bytes=0-65535"}}))});
  it("rejects private DNS targets before fetching",async()=>{const fetcher=vi.fn();await expect(new HttpDesignFileInspector(fetcher,async()=>["127.0.0.1"]).inspect("https://internal.example/file.png")).rejects.toMatchObject({code:"INVALID_DESIGN_FILE"});expect(fetcher).not.toHaveBeenCalled()});
  it("revalidates redirect targets and rejects private redirect destinations",async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(null,{status:302,headers:{location:"https://private.example/file.png"}}));const resolver=async(host:string)=>[host==="private.example"?"10.0.0.1":"203.0.113.10"];await expect(new HttpDesignFileInspector(fetcher,resolver).inspect("https://cdn.example/file.png")).rejects.toMatchObject({code:"INVALID_DESIGN_FILE"})});
  it("rejects unsupported or oversized files",async()=>{const html=new HttpDesignFileInspector(async()=>new Response(null,{status:200,headers:{"content-type":"text/html","content-length":"100"}}),publicDns);await expect(html.inspect("https://cdn.example/file")).rejects.toThrow("PNG or JPEG");const large=new HttpDesignFileInspector(async()=>new Response(null,{status:206,headers:{"content-type":"image/jpeg","content-range":"bytes 0-0/52428801"}}),publicDns);await expect(large.inspect("https://cdn.example/file.jpg")).rejects.toThrow("50 MB")});
  it("rejects MIME spoofing and oversized pixel dimensions",async()=>{const spoofed=new HttpDesignFileInspector(async()=>new Response(new TextEncoder().encode("not a png"),{status:200,headers:{"content-type":"image/png","content-length":"9"}}),publicDns);await expect(spoofed.inspect("https://cdn.example/fake.png")).rejects.toThrow("does not match");const huge=new HttpDesignFileInspector(async()=>new Response(png(20001,100),{status:206,headers:{"content-type":"image/png","content-range":"bytes 0-23/1024"}}),publicDns);await expect(huge.inspect("https://cdn.example/huge.png")).rejects.toThrow("20,000")});
});
