import {describe,expect,it,vi} from "vitest";
import {OrderAutomationControlService} from "../src/orders/automation-control.js";
import {orderAutomationJs} from "../src/admin/order-automation-ui.js";

describe("workspace order automation control",()=>{
  it("defaults to disabled when approval is absent",async()=>{const pool={query:vi.fn().mockResolvedValue({rows:[]})},service=new OrderAutomationControlService(pool as never);await expect(service.isEnabled("workspace-1")).resolves.toBe(false);await expect(service.get("workspace-1")).resolves.toMatchObject({enabled:false,approvedBy:null})});
  it("stores an audited approval transaction",async()=>{const query=vi.fn().mockResolvedValue({rows:[]}),client={query,release:vi.fn()},pool={connect:vi.fn().mockResolvedValue(client),query:vi.fn().mockResolvedValue({rows:[{workspace_id:"workspace-1",enabled:true,approved_by:"operator",approved_at:new Date("2026-08-13T00:00:00Z"),reason:"pilot approved",updated_at:new Date("2026-08-13T00:00:00Z")}]})},service=new OrderAutomationControlService(pool as never);await expect(service.set({workspaceId:"workspace-1",enabled:true,actorId:"operator",reason:"pilot approved"})).resolves.toMatchObject({enabled:true,approvedBy:"operator"});expect(query.mock.calls.some(call=>String(call[0]).includes("workspace_order_automation_actions"))).toBe(true);expect(query).toHaveBeenCalledWith("COMMIT")});
  it("returns bounded newest-first audit history",async()=>{const query=vi.fn().mockResolvedValue({rows:[{id:"action-1",action:"DISABLE",actor_id:"token-refresh",reason:"SHOPIFY 재인증 필요로 자동 중지",created_at:new Date("2026-08-13T01:00:00Z")}]}),service=new OrderAutomationControlService({query} as never);await expect(service.history("workspace-1",500)).resolves.toEqual([{id:"action-1",action:"DISABLE",actorId:"token-refresh",reason:"SHOPIFY 재인증 필요로 자동 중지",createdAt:"2026-08-13T01:00:00.000Z"}]);expect(query).toHaveBeenCalledWith(expect.stringContaining("ORDER BY created_at DESC"),["workspace-1",50])});
  it("reports in-flight work and workspace Printful rate usage",async()=>{const query=vi.fn().mockResolvedValue({rows:[{running:"2",held_remote_drafts:"1",queued:"3",rate_limited_waiting:"2",rate_limit_used:2,rate_limit_resets_at:new Date("2026-08-13T01:01:00Z")}]}),service=new OrderAutomationControlService({query} as never,2);await expect(service.activity("workspace-1")).resolves.toEqual({running:2,heldRemoteDrafts:1,queued:3,rateLimitedWaiting:2,rateLimitUsed:2,rateLimitCapacity:2,rateLimitResetsAt:"2026-08-13T01:01:00.000Z",requiresAttention:true});expect(query).toHaveBeenCalledWith(expect.stringContaining("WAITING_FOR_PRINTFUL_RATE_LIMIT"),["workspace-1"])});
  it("exposes prerequisite blockers before guarded approval",()=>{expect(orderAutomationJs).toContain("/order-automation");expect(orderAutomationJs).toContain("출시 승인");expect(orderAutomationJs).toContain("approval?.blockers");expect(orderAutomationJs).toContain("button.disabled")});
});
