import{describe,expect,it}from"vitest";
import{orderReconciliationScansJs}from"../src/admin/order-reconciliation-scans-ui.js";

describe("order reconciliation scan history UI",()=>{
  it("adds a safe workspace-scoped scan history tab",()=>{
    expect(orderReconciliationScansJs).toContain("스캔 이력");
    expect(orderReconciliationScansJs).toContain("/order-reconciliation/scans?limit=50");
    expect(orderReconciliationScansJs).toContain("remote_order_count");
    expect(orderReconciliationScansJs).toContain("issue_count");
    expect(orderReconciliationScansJs).toContain("actor_id");
    expect(orderReconciliationScansJs).toContain("MISSING_LOCAL_ORDER");
    expect(orderReconciliationScansJs).toContain("CANCELLATION_MISMATCH");
    expect(orderReconciliationScansJs).toContain("FINANCIAL_STATUS_MISMATCH");
    expect(orderReconciliationScansJs).toContain("유형별");
    expect(orderReconciliationScansJs).toContain("불일치 상세");
    expect(orderReconciliationScansJs).toContain("/issues");
    expect(orderReconciliationScansJs).toContain("issues?limit=100&offset=");
    expect(orderReconciliationScansJs).toContain("다음 100건");
    expect(orderReconciliationScansJs).toContain("reconciliation-issue-filter");
    expect(orderReconciliationScansJs).toContain("불일치 전체");
    expect(orderReconciliationScansJs).toContain("&issueType=");
    expect(orderReconciliationScansJs).toContain("reconciliation-order-search");
    expect(orderReconciliationScansJs).toContain("Shopify 주문 ID 검색");
    expect(orderReconciliationScansJs).toContain("orderSearch.maxLength=100");
    expect(orderReconciliationScansJs).toContain("&orderQuery=");
    expect(orderReconciliationScansJs).toContain("event.key==='Enter'");
    expect(orderReconciliationScansJs).toContain("scans?limit=50'+search");
    expect(orderReconciliationScansJs).toContain("event.preventDefault();load()");
    expect(orderReconciliationScansJs).toContain("insertAdjacentHTML");
    expect(orderReconciliationScansJs).toContain("encodeURIComponent(scanId)");
    expect(orderReconciliationScansJs).toContain("CSV 내보내기");
    expect(orderReconciliationScansJs).toContain("/export.csv");
    expect(orderReconciliationScansJs).toContain("URL.revokeObjectURL");
    expect(orderReconciliationScansJs).toContain("CSV 내보내기 사유를 입력해 주세요.");
    expect(orderReconciliationScansJs).toContain("method:'POST'");
    expect(orderReconciliationScansJs).toContain("reason:reason.trim()");
    expect(orderReconciliationScansJs).toContain("operatorInput.id='reconciliation-actor'");
    expect(orderReconciliationScansJs).toContain("담당자 ID");
    expect(orderReconciliationScansJs).toContain("operatorInput.maxLength=100");
    expect(orderReconciliationScansJs).toContain("drawerActor.value=value");
    expect(orderReconciliationScansJs).toContain("storzy.operatorId");
    expect(orderReconciliationScansJs).toContain("actorId:operator");
    expect(orderReconciliationScansJs).toContain("export_count");
    expect(orderReconciliationScansJs).toContain("latest_export");
    expect(orderReconciliationScansJs).toContain("latest_export?.reason");
    expect(orderReconciliationScansJs).toContain("/exports?limit=50");
    expect(orderReconciliationScansJs).toContain("내보내기 이력");
    expect(orderReconciliationScansJs).toContain("item.reason");
    expect(orderReconciliationScansJs).toContain("encodeURIComponent(workspace())");
    expect(()=>new Function(orderReconciliationScansJs)).not.toThrow();
  });
});
