import {randomUUID} from "node:crypto";
import {afterAll,describe,expect,it} from "vitest";
import {createPool} from "../src/db/pool.js";
const databaseUrl=process.env.TEST_DATABASE_URL,pool=databaseUrl?createPool(databaseUrl):null,suite=databaseUrl?describe:describe.skip;
afterAll(async()=>pool?.end());
suite("order automation queue safety on PostgreSQL",()=>{
  it("holds queued work on insert and on a later automation stop",async()=>{
    if(!pool)throw new Error("TEST_DATABASE_URL is required");
    const c=await pool.connect(),workspaceId=randomUUID(),receiptId=randomUUID(),orderId=randomUUID(),jobId=randomUUID();
    try{await c.query("BEGIN");await c.query("INSERT INTO workspaces(id,name) VALUES($1,'queue safety test')",[workspaceId]);await c.query("INSERT INTO shopify_order_webhook_receipts(id,webhook_id,workspace_id,topic,shop_domain,payload_digest,payload) VALUES($1,$2,$3,'orders/paid','test.myshopify.com','digest','{}')",[receiptId,randomUUID(),workspaceId]);await c.query(`INSERT INTO commerce_orders(id,workspace_id,shopify_order_id,order_name,currency,revenue_minor,approved_variable_cost_minor,current_variable_cost_minor,shipping_country,item_count,financial_status,status,decision_reasons,margin_basis_points,rule_version,source_webhook_id) VALUES($1,$2,$3,'#1','USD',3900,1500,1500,'US',1,'paid','READY','[]',6000,'test',$4)`,[orderId,workspaceId,randomUUID(),receiptId]);await c.query("INSERT INTO printful_order_jobs(id,commerce_order_id,workspace_id,external_id) VALUES($1,$2,$3,$4)",[jobId,orderId,workspaceId,randomUUID()]);let state=await c.query<{status:string}>("SELECT status FROM printful_order_jobs WHERE id=$1",[jobId]);expect(state.rows[0]?.status).toBe("HELD");await c.query("INSERT INTO workspace_order_automation_controls(workspace_id,enabled,approved_by,approved_at,reason) VALUES($1,true,'operator',now(),'approved')",[workspaceId]);await c.query("UPDATE printful_order_jobs SET status='PENDING_DRAFT',finished_at=NULL,last_error=NULL WHERE id=$1",[jobId]);await c.query("UPDATE workspace_order_automation_controls SET enabled=false,approved_by=NULL,approved_at=NULL,reason='manual stop' WHERE workspace_id=$1",[workspaceId]);state=await c.query("SELECT status FROM printful_order_jobs WHERE id=$1",[jobId]);const order=await c.query<{status:string;decision_reasons:string[]}>("SELECT status,decision_reasons FROM commerce_orders WHERE id=$1",[orderId]);expect(state.rows[0]?.status).toBe("HELD");expect(order.rows[0]).toMatchObject({status:"HELD",decision_reasons:["ORDER_AUTOMATION_SUSPENDED"]});}finally{await c.query("ROLLBACK");c.release()}
  });
});
