import{describe,expect,it,vi}from"vitest";
import{OrderExceptionService}from"../src/orders/exception-service.js";
function fixture(decisionReasons=["COST_SPIKE"],automationEnabled=true){const calls:string[]=[];const query=vi.fn(async(sql:string)=>{calls.push(sql);if(sql==="BEGIN"||sql==="COMMIT"||sql==="ROLLBACK")return{};if(sql.includes("FROM commerce_orders WHERE id="))return{rows:[{id:"o",shopify_order_id:"gid://shopify/Order/1",currency:"USD",revenue_minor:"3900",approved_variable_cost_minor:"2000",current_variable_cost_minor:"2000",shipping_country:"US",item_count:1,financial_status:"paid",status:"HELD",decision_reasons:decisionReasons}]};if(sql.includes("FROM order_exception_actions"))return{rows:[]};if(sql.includes("workspace_order_automation_controls"))return{rows:[{enabled:automationEnabled}]};return{rows:[],rowCount:1}}),release=vi.fn(),pool={connect:vi.fn().mockResolvedValue({query,release})}as never;return{service:new OrderExceptionService(pool,new Set(["US"]),{maxOrderAmountMinor:50000n,maxItemCount:10,maxCostIncreaseBasisPoints:1000}),query,calls,release}}
describe("Order exception actions",()=>{
  it("requires a reason for manual approval",async()=>{const{service}=fixture();await expect(service.act({workspaceId:"w",orderId:"o",action:"MANUAL_APPROVE",actorId:"admin",idempotencyKey:"k"})).rejects.toMatchObject({code:"INVALID_INPUT"})});
  it("audits and requeues a manual approval while automation is enabled",async()=>{const{service,calls,release}=fixture();await expect(service.act({workspaceId:"w",orderId:"o",action:"MANUAL_APPROVE",actorId:"admin",reason:"Verified with supplier",idempotencyKey:"k"})).resolves.toMatchObject({status:"READY",duplicate:false});expect(calls.some(x=>x.includes("INSERT INTO order_exception_actions"))).toBe(true);expect(calls.some(x=>x.includes("INSERT INTO printful_order_jobs"))).toBe(true);expect(release).toHaveBeenCalled()});
  it("keeps manual approval held while automation is stopped",async()=>{const{service,calls}=fixture(["COST_SPIKE"],false);await expect(service.act({workspaceId:"w",orderId:"o",action:"MANUAL_APPROVE",actorId:"admin",reason:"Verified",idempotencyKey:"stopped"})).resolves.toMatchObject({status:"HELD",reasons:["ORDER_AUTOMATION_SUSPENDED"]});expect(calls.some(x=>x.includes("INSERT INTO printful_order_jobs"))).toBe(false)});
  for(const protectedReason of["RECONCILIATION_REPLAY_REVIEW","FINANCIAL_STATUS_SYNC_REVIEW"])it("requires policy revalidation for "+protectedReason,async()=>{const{service,calls}=fixture([protectedReason]);await expect(service.act({workspaceId:"w",orderId:"o",action:"MANUAL_APPROVE",actorId:"admin",reason:"Approve recovery",idempotencyKey:protectedReason})).rejects.toMatchObject({code:"ORDER_NOT_ACTIONABLE"});expect(calls.some(x=>x.includes("INSERT INTO printful_order_jobs"))).toBe(false)});
});
