import{describe,expect,it,vi}from"vitest";import{verifyPostDeployment}from"../src/deployment/post-deploy-verifier.js";
const response=(body:unknown,status=200,headers:Record<string,string>={})=>{const value=body&&typeof body==="object"&&"status"in body&&body.status==="ready"&&"checks"in body?{...body,checks:{...(body.checks as object),schema:true}}:body;return new Response(JSON.stringify(value),{status,headers:{"Content-Type":"application/json",...headers}})};
const healthyProcesses=()=>response({data:{healthy:true,summary:{healthy:15,stale:0,failed:0,neverSeen:0,total:15},items:[]}});
describe("배포 후 검증",()=>{
  it("헬스·보안·인증·프로세스·파일럿 API를 읽기 전용으로 검증한다",async()=>{const fetchMock=vi.fn(async(url:string|URL|Request,init?:RequestInit)=>{const path=new URL(String(url)).pathname;if(path==="/health")return response({status:"ok",service:"storzy"});if(path==="/ready")return response({status:"ready",service:"storzy",checks:{database:true}},200,{"Cache-Control":"no-store"});if(path==="/admin")return response("html",200,{"Content-Security-Policy":"default-src 'self'; frame-ancestors 'none'","X-Frame-Options":"DENY","Cache-Control":"no-store, private"});if(path==="/api/admin/workspaces"&&!init?.headers)return response({error:{}},401,{"WWW-Authenticate":'Bearer realm="storzy-admin"'});if(path==="/api/admin/workspaces")return response({data:[{id:"workspace-1"}]});if(path==="/api/admin/process-health")return healthyProcesses();return response({data:{ready:false,completed:3,total:6,nextStep:{label:"Shopify 연결"}}})}),fetch=fetchMock as typeof globalThis.fetch;const result=await verifyPostDeployment({baseUrl:"https://app.example",adminToken:"secret",fetch});expect(result.healthy).toBe(true);expect(result.workspaceId).toBe("workspace-1");expect(result.pilot).toEqual({ready:false,completed:3,total:6,nextStep:"Shopify 연결"});expect(result.processes).toEqual({healthy:15,stale:0,failed:0,neverSeen:0,total:15});expect(fetch).toHaveBeenCalledTimes(7);expect(JSON.stringify(fetchMock.mock.calls)).toContain("Bearer secret")});
  it("무인증 API가 열려 있으면 배포 실패로 판정한다",async()=>{const fetch=vi.fn(async(url:string|URL|Request)=>{const path=new URL(String(url)).pathname;if(path==="/health")return response({status:"ok",service:"storzy"});if(path==="/ready")return response({status:"ready",checks:{database:true}},200,{"Cache-Control":"no-store"});if(path==="/admin")return response("html",200,{"Content-Security-Policy":"frame-ancestors 'none'","X-Frame-Options":"DENY","Cache-Control":"no-store"});if(path==="/api/admin/process-health")return healthyProcesses();if(path==="/api/admin/workspaces")return response({data:[]});return response({})})as typeof globalThis.fetch;const result=await verifyPostDeployment({baseUrl:"https://app.example",adminToken:"secret",fetch});expect(result.healthy).toBe(false);expect(result.checks.find(check=>check.key==="AUTH_GUARD")?.ok).toBe(false)});
  it("프로세스가 시작될 때까지 재시도한다",async()=>{let processCalls=0;const sleep=vi.fn(async()=>{}),fetch=vi.fn(async(url:string|URL|Request,init?:RequestInit)=>{const path=new URL(String(url)).pathname;if(path==="/health")return response({status:"ok",service:"storzy"});if(path==="/ready")return response({status:"ready",checks:{database:true}},200,{"Cache-Control":"no-store"});if(path==="/admin")return response("html",200,{"Content-Security-Policy":"frame-ancestors 'none'","X-Frame-Options":"DENY","Cache-Control":"no-store"});if(path==="/api/admin/workspaces"&&!init?.headers)return response({},401,{"WWW-Authenticate":'Bearer realm="storzy-admin"'});if(path==="/api/admin/workspaces")return response({data:[]});if(path==="/api/admin/process-health"){processCalls++;return response({data:{healthy:processCalls===2,summary:{healthy:processCalls===2?15:14,stale:processCalls===2?0:1,failed:0,neverSeen:0,total:15},items:[]}})}return response({})})as typeof globalThis.fetch;const result=await verifyPostDeployment({baseUrl:"https://app.example",adminToken:"secret",fetch,processAttempts:2,processRetryMs:1,sleep});expect(result.checks.find(check=>check.key==="PROCESS_HEALTH")?.ok).toBe(true);expect(processCalls).toBe(2);expect(sleep).toHaveBeenCalledWith(1)});
  it("필수 역할 수가 15개가 아니면 실패한다",async()=>{const fetch=vi.fn(async(url:string|URL|Request,init?:RequestInit)=>{const path=new URL(String(url)).pathname;if(path==="/health")return response({status:"ok",service:"storzy"});if(path==="/ready")return response({status:"ready",checks:{database:true}},200,{"Cache-Control":"no-store"});if(path==="/admin")return response("html",200,{"Content-Security-Policy":"frame-ancestors 'none'","X-Frame-Options":"DENY","Cache-Control":"no-store"});if(path==="/api/admin/workspaces"&&!init?.headers)return response({},401,{"WWW-Authenticate":'Bearer realm="storzy-admin"'});if(path==="/api/admin/workspaces")return response({data:[]});if(path==="/api/admin/process-health")return response({data:{healthy:true,summary:{healthy:13,stale:0,failed:0,neverSeen:0,total:13}}});return response({})})as typeof globalThis.fetch;const result=await verifyPostDeployment({baseUrl:"https://app.example",adminToken:"secret",fetch});expect(result.healthy).toBe(false);expect(result.checks.find(check=>check.key==="PROCESS_HEALTH")?.ok).toBe(false)});
  it("경로나 자격증명이 포함된 기준 URL을 거부한다",async()=>{await expect(verifyPostDeployment({baseUrl:"https://user:pass@app.example/admin",adminToken:"secret",fetch:vi.fn()as never})).rejects.toThrow("Base URL")});
});
