import{describe,expect,it,vi}from"vitest";
import{PrintfulOrderJobStore,type OrderJob}from"../src/orders/printful-job-store.js";

const job:OrderJob={id:"job-1",orderId:"order-1",workspaceId:"workspace-1",externalId:"external-1",phase:"READY_CONFIRM",remoteOrderId:"99",attempt:1};

describe("Printful order job lease ownership",()=>{
  it("extends only a live lease owned by the worker",async()=>{const query=vi.fn().mockResolvedValue({rowCount:1}),store=new PrintfulOrderJobStore({query}as never);await expect(store.extendLease("job-1","worker-1",60)).resolves.toBe(true);expect(String(query.mock.calls[0]?.[0])).toContain("status='RUNNING'");expect(String(query.mock.calls[0]?.[0])).toContain("lease_expires_at>now()")});
  it("does not submit the commerce order after lease ownership is lost",async()=>{const statements:string[]=[],query=vi.fn(async(sql:string)=>{statements.push(sql);if(sql.startsWith("UPDATE printful_order_jobs"))return{rowCount:0,rows:[]};return{rowCount:null,rows:[]}}),client={query,release:vi.fn()},store=new PrintfulOrderJobStore({connect:vi.fn(async()=>client)}as never);await expect(store.success(job,"worker-1",{})).resolves.toBe(false);expect(statements).toContain("ROLLBACK");expect(statements.some(sql=>sql.startsWith("UPDATE commerce_orders"))).toBe(false);expect(statements).not.toContain("COMMIT")});
  it("does not hold the commerce order after lease ownership is lost",async()=>{const statements:string[]=[],query=vi.fn(async(sql:string)=>{statements.push(sql);if(sql.startsWith("UPDATE printful_order_jobs"))return{rowCount:0,rows:[]};return{rowCount:null,rows:[]}}),client={query,release:vi.fn()},store=new PrintfulOrderJobStore({connect:vi.fn(async()=>client)}as never);await expect(store.hold(job,"worker-1","STALE_WORKER")).resolves.toBe(false);expect(statements.some(sql=>sql.startsWith("UPDATE commerce_orders"))).toBe(false);expect(statements).toContain("ROLLBACK")});
  it("commits recovery history in the same transaction as submission",async()=>{const statements:string[]=[],query=vi.fn(async(sql:string,_params?:unknown[])=>{statements.push(sql);return sql.startsWith("UPDATE printful_order_jobs")?{rowCount:1,rows:[{id:"job-1"}]}:{rowCount:1,rows:[]}}),client={query,release:vi.fn()},store=new PrintfulOrderJobStore({connect:vi.fn(async()=>client)}as never);await expect(store.success(job,"worker-1",{},"CONFIRMATION_RECOVERED")).resolves.toBe(true);expect(statements.some(sql=>sql.includes("INSERT INTO printful_order_job_events"))).toBe(true);expect(query.mock.calls.find(call=>String(call[0]).includes("printful_order_job_events"))?.[1]).toEqual(expect.arrayContaining(["CONFIRMATION_RECOVERED","worker-1","99"]));expect(statements.at(-1)).toBe("COMMIT")});
});
