import{describe,expect,it,vi}from"vitest";
import{PrintfulOrderWorker}from"../src/orders/printful-worker.js";
import{ProviderHttpError}from"../src/integrations/http.js";
const context={request:{recipient:{},order_items:[]},currency:"USD",revenueMinor:3900n,approvedCostMinor:2000n};
const job=(phase:"PENDING_DRAFT"|"WAITING_COST"|"READY_CONFIRM")=>({id:"j",orderId:"o",workspaceId:"workspace-1",externalId:"e",phase,remoteOrderId:phase==="PENDING_DRAFT"?null:"99",attempt:2});
describe("Printful order worker",()=>{
  it("holds a draft whose calculated cost exceeds revenue",async()=>{const selected=job("WAITING_COST"),store={claim:vi.fn().mockResolvedValue(selected),automationEnabled:vi.fn().mockResolvedValue(true),payload:vi.fn().mockResolvedValue(context),hold:vi.fn(),waitCost:vi.fn(),readyConfirm:vi.fn(),retry:vi.fn()},client={getOrder:vi.fn().mockResolvedValue({data:{id:99,status:"draft",costs:{calculation_status:"done",currency:"USD",total:"40.00"}}})};await new PrintfulOrderWorker(store as never,client as never,"w").tick();expect(store.hold).toHaveBeenCalledWith(selected,"w","NEGATIVE_MARGIN",4000n,"USD");expect(store.readyConfirm).not.toHaveBeenCalled()});
  it("confirms only a prevalidated draft",async()=>{const selected=job("READY_CONFIRM"),store={claim:vi.fn().mockResolvedValue(selected),automationEnabled:vi.fn().mockResolvedValue(true),success:vi.fn(),hold:vi.fn(),retry:vi.fn()},response={data:{id:99,status:"pending",costs:{calculation_status:"done",currency:"USD",total:"20.00"}}},client={getOrder:vi.fn().mockResolvedValue({data:{id:99,status:"draft",costs:{calculation_status:"done",currency:"USD",total:"20.00"}}}),confirmOrder:vi.fn().mockResolvedValue(response)};await new PrintfulOrderWorker(store as never,client as never,"w").tick();expect(client.confirmOrder).toHaveBeenCalledWith("99");expect(store.success).toHaveBeenCalledWith(selected,"w",response)});
  it("recovers an already confirmed remote order without confirming twice",async()=>{const selected=job("READY_CONFIRM"),store={claim:vi.fn().mockResolvedValue(selected),automationEnabled:vi.fn().mockResolvedValue(true),success:vi.fn().mockResolvedValue(true),hold:vi.fn(),retry:vi.fn()},response={data:{id:99,status:"inprocess",costs:{calculation_status:"done",currency:"USD",total:"20.00"}}},client={getOrder:vi.fn().mockResolvedValue(response),confirmOrder:vi.fn()};await new PrintfulOrderWorker(store as never,client as never,"w").tick();expect(store.success).toHaveBeenCalledWith(selected,"w",response,"CONFIRMATION_RECOVERED");expect(client.confirmOrder).not.toHaveBeenCalled()});
  it("does not confirm after losing the job lease",async()=>{const selected=job("READY_CONFIRM"),store={claim:vi.fn().mockResolvedValue(selected),automationEnabled:vi.fn().mockResolvedValue(true),extendLease:vi.fn().mockResolvedValue(false),success:vi.fn(),hold:vi.fn(),retry:vi.fn()},client={getOrder:vi.fn().mockResolvedValue({data:{id:99,status:"draft",costs:{calculation_status:"done",currency:"USD",total:"20.00"}}}),confirmOrder:vi.fn()};await new PrintfulOrderWorker(store as never,client as never,"w").tick();expect(store.extendLease).toHaveBeenCalledWith("j","w",60);expect(client.confirmOrder).not.toHaveBeenCalled();expect(store.hold).not.toHaveBeenCalled();expect(store.retry).not.toHaveBeenCalled()});
  it("defers confirmation without consuming an attempt when workspace capacity is exhausted",async()=>{const selected=job("READY_CONFIRM"),store={claim:vi.fn().mockResolvedValue(selected),automationEnabled:vi.fn().mockResolvedValue(true),deferRateLimit:vi.fn(),success:vi.fn(),hold:vi.fn(),retry:vi.fn()},client={getOrder:vi.fn().mockResolvedValue({data:{id:99,status:"draft",costs:{calculation_status:"done",currency:"USD",total:"20.00"}}}),confirmOrder:vi.fn()},limiter={acquire:vi.fn().mockResolvedValue({allowed:false,retryAfterMs:17000})};await new PrintfulOrderWorker(store as never,client as never,"w",8,1000,limiter).tick();expect(store.deferRateLimit).toHaveBeenCalledWith(selected,"w",17000);expect(client.confirmOrder).not.toHaveBeenCalled();expect(store.hold).not.toHaveBeenCalled()});
  it("honors provider Retry-After without consuming an attempt",async()=>{const selected=job("READY_CONFIRM"),store={claim:vi.fn().mockResolvedValue(selected),automationEnabled:vi.fn().mockResolvedValue(true),deferRateLimit:vi.fn(),success:vi.fn(),hold:vi.fn(),retry:vi.fn()},client={getOrder:vi.fn().mockResolvedValue({data:{id:99,status:"draft",costs:{calculation_status:"done",currency:"USD",total:"20.00"}}}),confirmOrder:vi.fn().mockRejectedValue(new ProviderHttpError("printful",429,"limited",23000))};await new PrintfulOrderWorker(store as never,client as never,"w").tick();expect(store.deferRateLimit).toHaveBeenCalledWith(selected,"w",23000);expect(store.retry).not.toHaveBeenCalled();expect(store.hold).not.toHaveBeenCalled()});
  it.each(["PENDING_DRAFT","WAITING_COST","READY_CONFIRM"] as const)("blocks %s external calls while automation is stopped",async phase=>{const selected=job(phase),store={claim:vi.fn().mockResolvedValue(selected),automationEnabled:vi.fn().mockResolvedValue(false),hold:vi.fn(),retry:vi.fn()},client={createDraftOrder:vi.fn(),getOrder:vi.fn(),confirmOrder:vi.fn()},worker=new PrintfulOrderWorker(store as never,client as never,"w");await expect(worker.tick()).resolves.toBe(true);expect(store.hold).toHaveBeenCalledWith(selected,"w","ORDER_AUTOMATION_SUSPENDED");expect(client.createDraftOrder).not.toHaveBeenCalled();expect(client.getOrder).not.toHaveBeenCalled();expect(client.confirmOrder).not.toHaveBeenCalled()});
});
