import {describe,expect,it,vi} from "vitest";
import {PrivacyAlertDeliveryService,SignedPrivacyAlertWebhook} from "../src/privacy/alert-delivery-service.js";

const payload={id:"alert-1",level:"OVERDUE",requestType:"SHOP_REDACT",shopDomain:"store.myshopify.com",dueAt:"2026-08-01T00:00:00.000Z",openedAt:"2026-08-02T00:00:00.000Z"};

describe("privacy alert delivery",()=>{
  it("requires HTTPS and signs webhook requests",async()=>{expect(()=>new SignedPrivacyAlertWebhook("http://example.com/hook","0123456789abcdef")).toThrow("HTTPS");const fetcher=vi.fn().mockResolvedValue(new Response(null,{status:204})),sender=new SignedPrivacyAlertWebhook("https://example.com/hook","0123456789abcdef",fetcher);await expect(sender.send(payload)).resolves.toEqual({status:204});const init=fetcher.mock.calls[0]?.[1] as RequestInit,headers=init.headers as Record<string,string>;expect(headers["X-Storzy-Signature"]).toMatch(/^sha256=[a-f0-9]{64}$/);expect(headers["X-Storzy-Timestamp"]).toMatch(/^\d+$/);expect(init.body).toBe(JSON.stringify(payload));});

  it("claims and marks a delivered alert as sent",async()=>{const query=vi.fn(async(sql:string)=>{if(sql.startsWith("WITH candidates"))return{rows:[{id:"delivery-1",alert_id:"alert-1",attempts:1,level:"OVERDUE",request_type:"SHOP_REDACT",shop_domain:"store.myshopify.com",due_at:new Date(payload.dueAt),opened_at:new Date(payload.openedAt)}]};return{rows:[],rowCount:1};}),sender={send:vi.fn().mockResolvedValue({status:202})},service=new PrivacyAlertDeliveryService({query} as never,sender,{workerId:"worker-1",maxAttempts:6,leaseSeconds:30});await expect(service.deliverBatch()).resolves.toEqual({claimed:1,sent:1,failed:0});expect(sender.send).toHaveBeenCalledWith(payload);expect(query.mock.calls.some(call=>String(call[0]).includes("status='SENT'"))).toBe(true);});

  it("records failure and schedules exponential retry",async()=>{const calls:Array<[string,unknown[]|undefined]>=[],query=vi.fn(async(sql:string,params?:unknown[])=>{calls.push([sql,params]);if(sql.startsWith("WITH candidates"))return{rows:[{id:"delivery-1",alert_id:"alert-1",attempts:3,level:"FAILED",request_type:"CUSTOMERS_REDACT",shop_domain:"store.myshopify.com",due_at:new Date(payload.dueAt),opened_at:new Date(payload.openedAt)}]};return{rows:[],rowCount:1};}),sender={send:vi.fn().mockRejectedValue(Object.assign(new Error("Alert webhook returned 503"),{status:503}))},service=new PrivacyAlertDeliveryService({query} as never,sender,{workerId:"worker-1",maxAttempts:6,leaseSeconds:30});await expect(service.deliverBatch()).resolves.toEqual({claimed:1,sent:0,failed:1});const failed=calls.find(([sql,params])=>sql.includes("status='FAILED'")&&params?.length===5);expect(failed?.[1]).toEqual(["delivery-1","worker-1",503,"Alert webhook returned 503",120]);});

  it("delivers one signed maintenance alert for the current incident episode",async()=>{const opened=new Date("2026-08-20T00:00:00.000Z"),updated=new Date("2026-08-20T01:00:00.000Z"),query=vi.fn(async(sql:string)=>sql.startsWith("WITH candidates")?{rows:[{id:"maintenance-delivery-1",incident_id:"incident-1",attempts:1,incident_type:"SLA_SCAN_FAILED",last_error:"database unavailable",opened_at:opened,updated_at:updated}]}:{rows:[],rowCount:1}),sender={send:vi.fn().mockResolvedValue({status:202})},service=new PrivacyAlertDeliveryService({query}as never,sender,{workerId:"worker-1",maxAttempts:6,leaseSeconds:30});await expect(service.deliverMaintenanceBatch()).resolves.toEqual({claimed:1,sent:1,failed:0});expect(sender.send).toHaveBeenCalledWith({category:"PRIVACY_MAINTENANCE",id:"incident-1",incidentType:"SLA_SCAN_FAILED",lastError:"database unavailable",openedAt:opened.toISOString(),updatedAt:updated.toISOString()});expect(query.mock.calls.some(call=>String(call[0]).includes("ON CONFLICT(incident_id,incident_opened_at) DO NOTHING"))).toBe(true);expect(query.mock.calls.some(call=>String(call[0]).includes("UPDATE privacy_maintenance_alert_deliveries SET status='SENT'"))).toBe(true);});

  it("retries a failed maintenance delivery with bounded exponential backoff",async()=>{const calls:Array<[string,unknown[]|undefined]>=[],query=vi.fn(async(sql:string,params?:unknown[])=>{calls.push([sql,params]);return sql.startsWith("WITH candidates")?{rows:[{id:"maintenance-delivery-1",incident_id:"incident-1",attempts:4,incident_type:"UNINSTALL_RETENTION_FAILED",last_error:null,opened_at:new Date(),updated_at:new Date()}]}:{rows:[],rowCount:1}}),sender={send:vi.fn().mockRejectedValue(Object.assign(new Error("Alert webhook returned 429"),{status:429}))},service=new PrivacyAlertDeliveryService({query}as never,sender,{workerId:"worker-1",maxAttempts:6,leaseSeconds:30});await expect(service.deliverMaintenanceBatch()).resolves.toEqual({claimed:1,sent:0,failed:1});expect(calls.find(([sql,params])=>sql.includes("privacy_maintenance_alert_deliveries SET status='FAILED'")&&params?.length===5)?.[1]).toEqual(["maintenance-delivery-1","worker-1",429,"Alert webhook returned 429",240]);});

  it("recovers expired request and maintenance delivery leases before claiming",async()=>{const calls:string[]=[],query=vi.fn(async(sql:string)=>{calls.push(sql);return sql.startsWith("WITH candidates")?{rows:[]}:{rows:[],rowCount:1}}),service=new PrivacyAlertDeliveryService({query}as never,{send:vi.fn()},{workerId:"worker-1",maxAttempts:6,leaseSeconds:30});await service.deliverBatch();await service.deliverMaintenanceBatch();const recoveries=calls.filter(sql=>sql.includes("DELIVERY_LEASE_EXPIRED"));expect(recoveries).toHaveLength(2);expect(recoveries[0]).toContain("status='RUNNING' AND lease_expires_at<=now()");expect(recoveries[1]).toContain("privacy_maintenance_alert_deliveries");});
});
