import{describe,expect,it,vi}from"vitest";import{ScheduledOrderReconciliation}from"../src/orders/scheduled-reconciliation.js";

const lockClient=(locked:boolean)=>({query:vi.fn(async(sql:string)=>({rows:sql.includes("try_advisory")?[{locked}]:[{pg_advisory_unlock:true}]})),release:vi.fn()});

describe("scheduled order reconciliation",()=>{
  it("recovers interrupted runs, scans workspaces, and records the new run",async()=>{const client=lockClient(true),query=vi.fn(async(sql:string,_params?:unknown[])=>sql.startsWith("SELECT c.workspace_id")?{rows:[{workspace_id:"w1",account_label:"stale.myshopify.com"}]}:sql.includes("PROCESS_INTERRUPTED_BEFORE_COMPLETION")?{rows:[{id:"stale-run"}],rowCount:1}:{rows:[]}),pool={connect:vi.fn(async()=>client),query},access={resolve:vi.fn(async()=>({shopDomain:"store.myshopify.com",accessToken:"secret"}))},recorder={record:vi.fn(async()=>({issues:0}))},fetchOrders=vi.fn(async()=>[{id:"gid://shopify/Order/1",updatedAt:"2026-08-12T00:00:00Z",cancelledAt:null,financialStatus:"PAID"}]),scanner=new ScheduledOrderReconciliation(pool as never,access,recorder,fetchOrders,()=>new Date("2026-08-12T12:00:00Z"));await expect(scanner.run({hours:24,actorId:"scheduler",apiVersion:"2026-07"})).resolves.toMatchObject({skipped:false,recoveredRuns:1,workspaces:1,succeeded:1,failed:0});expect(fetchOrders).toHaveBeenCalledWith(expect.objectContaining({shopDomain:"store.myshopify.com",since:new Date("2026-08-11T12:00:00Z")}));expect(query.mock.calls.some(call=>String(call[0]).includes("PROCESS_INTERRUPTED_BEFORE_COMPLETION"))).toBe(true);expect(query.mock.calls.some(call=>String(call[0]).startsWith("INSERT INTO order_reconciliation_runs"))).toBe(true);expect(client.query).toHaveBeenCalledWith(expect.stringContaining("pg_advisory_unlock"));});

  it("redacts access tokens and bounds provider errors",async()=>{const token="sensitive-token",client=lockClient(true),query=vi.fn(async(sql:string,_params?:unknown[])=>sql.startsWith("SELECT c.workspace_id")?{rows:[{workspace_id:"w1",account_label:"store.myshopify.com"}]}:{rows:[]}),scanner=new ScheduledOrderReconciliation({connect:vi.fn(async()=>client),query}as never,{resolve:vi.fn(async()=>({shopDomain:"store.myshopify.com",accessToken:token}))},{record:vi.fn()}as never,vi.fn(async()=>{throw new Error(token+'\n'+"x".repeat(700))}));const result=await scanner.run({hours:24,actorId:"scheduler",apiVersion:"2026-07"}),error=result.results[0]?.error??"";expect(error).toContain("[REDACTED]");expect(error).not.toContain(token);expect(error).not.toContain("\n");expect(error.length).toBeLessThanOrEqual(500);const update=query.mock.calls.find(call=>String(call[0]).startsWith("UPDATE order_reconciliation_runs SET status="));expect(JSON.stringify(update?.[1])).not.toContain(token);});

  it("skips without changing ledgers when another scanner owns the lock",async()=>{const client=lockClient(false),pool={connect:vi.fn(async()=>client),query:vi.fn()},scanner=new ScheduledOrderReconciliation(pool as never,{resolve:vi.fn()}as never,{record:vi.fn()}as never);await expect(scanner.run({hours:24,actorId:"scheduler",apiVersion:"2026-07"})).resolves.toMatchObject({skipped:true,reason:"ALREADY_RUNNING"});expect(pool.query).not.toHaveBeenCalled();expect(client.release).toHaveBeenCalled();});
});
