import{describe,expect,it,vi}from"vitest";
import{CredentialCipher}from"../src/integrations/credential-cipher.js";
import{IntegrationConnectionRepository}from"../src/integrations/connection-repository.js";

describe("Shopify app uninstall repository",()=>{
  it("destroys credentials and records the uninstall once",async()=>{const calls:Array<[string,unknown[]|undefined]>=[],query=vi.fn(async(sql:string,params?:unknown[])=>{calls.push([sql,params]);if(sql.startsWith("INSERT INTO shopify_app_uninstall_receipts"))return{rows:[{id:"receipt-1"}],rowCount:1};if(sql.startsWith("SELECT id,workspace_id,status"))return{rows:[{id:"connection-1",workspace_id:"workspace-1",status:"CONNECTED"}],rowCount:1};return{rows:[],rowCount:1}}),client={query,release:vi.fn()},repository=new IntegrationConnectionRepository({connect:vi.fn(async()=>client)}as never,new CredentialCipher(Buffer.alloc(32,7)));await expect(repository.revokeShopifyInstallation({shopDomain:"store.myshopify.com",webhookId:"delivery-1"})).resolves.toMatchObject({duplicate:false,workspaceMatched:true,workspaceId:"workspace-1"});const update=calls.find(([sql])=>sql.startsWith("UPDATE integration_connections"));expect(update?.[0]).toContain("encryption_key_version='destroyed'");expect(update?.[1]?.slice(1)).toEqual([expect.any(Buffer),expect.any(Buffer),expect.any(Buffer)]);expect(calls.some(([sql])=>sql.includes("'shopify-app-uninstalled'"))).toBe(true);expect(query).toHaveBeenCalledWith("COMMIT")});
  it("accepts a repeated delivery without changing the connection",async()=>{const query=vi.fn(async(sql:string)=>sql.startsWith("INSERT INTO shopify_app_uninstall_receipts")?{rows:[],rowCount:0}:{rows:[],rowCount:null}),client={query,release:vi.fn()},repository=new IntegrationConnectionRepository({connect:vi.fn(async()=>client)}as never,new CredentialCipher(Buffer.alloc(32,7)));await expect(repository.revokeShopifyInstallation({shopDomain:"store.myshopify.com",webhookId:"delivery-1"})).resolves.toMatchObject({duplicate:true});expect(query.mock.calls.some(call=>String(call[0]).startsWith("UPDATE integration_connections"))).toBe(false)});
  it("links a new uninstall receipt to an already disconnected workspace without rewriting credentials",async()=>{const calls:string[]=[],query=vi.fn(async(sql:string)=>{calls.push(sql);if(sql.startsWith("INSERT INTO shopify_app_uninstall_receipts"))return{rows:[{id:"receipt-2"}],rowCount:1};if(sql.startsWith("SELECT id,workspace_id,status"))return{rows:[{id:"connection-1",workspace_id:"workspace-1",status:"DISCONNECTED"}],rowCount:1};return{rows:[],rowCount:1}}),client={query,release:vi.fn()},repository=new IntegrationConnectionRepository({connect:vi.fn(async()=>client)}as never,new CredentialCipher(Buffer.alloc(32,7)));await expect(repository.revokeShopifyInstallation({shopDomain:"store.myshopify.com",webhookId:"delivery-2"})).resolves.toMatchObject({workspaceMatched:true,workspaceId:"workspace-1",alreadyDisconnected:true});expect(calls.some(sql=>sql.startsWith("UPDATE integration_connections"))).toBe(false);expect(calls.some(sql=>sql.startsWith("INSERT INTO integration_connection_actions"))).toBe(false);expect(calls.some(sql=>sql.startsWith("UPDATE shopify_app_uninstall_receipts"))).toBe(true)});
});
