import{describe,expect,it,vi}from"vitest";
import{ShopifyGraphqlError}from"../src/integrations/shopify.js";
import{ShopifyPublicationWorker}from"../src/shopify/worker.js";
import{ShopifyFulfillmentWorker}from"../src/fulfillment/worker.js";
import{StorePublicationWorker}from"../src/storefront/publication-worker.js";

describe("Shopify throttle-aware workers",()=>{
  it("defers product publication without consuming an attempt",async()=>{const job={id:"job-1",revisionId:"revision-1",workspaceId:"workspace-1",attempt:2},store={claim:vi.fn().mockResolvedValue(job),extend:vi.fn(),payload:vi.fn().mockResolvedValue({}),deferRateLimit:vi.fn(),retry:vi.fn(),fail:vi.fn()},publisher={publish:vi.fn().mockRejectedValue(new ShopifyGraphqlError([],429,2500))},worker=new ShopifyPublicationWorker(store as never,publisher as never,{} as never,{workerId:"worker",leaseSeconds:60,maxAttempts:8,pollMs:100});await expect(worker.processOne()).resolves.toBe(true);expect(store.deferRateLimit).toHaveBeenCalledWith("job-1","worker",2500);expect(store.retry).not.toHaveBeenCalled();expect(store.fail).not.toHaveBeenCalled()});
  it("defers fulfillment without consuming an attempt",async()=>{const job={id:"job-2",shipmentId:"shipment-1",workspaceId:"workspace-1",attempt:2},store={claim:vi.fn().mockResolvedValue(job),context:vi.fn().mockResolvedValue({}),deferRateLimit:vi.fn(),retry:vi.fn(),fail:vi.fn(),success:vi.fn()},publisher={publish:vi.fn().mockRejectedValue(new ShopifyGraphqlError([],429,3000))},worker=new ShopifyFulfillmentWorker(store as never,publisher as never,"worker");await expect(worker.tick()).resolves.toBe(true);expect(store.deferRateLimit).toHaveBeenCalledWith(job,"worker",3000);expect(store.retry).not.toHaveBeenCalled();expect(store.fail).not.toHaveBeenCalled()});
  it("defers store page publication without consuming an attempt",async()=>{const job={id:"job-3",storeDraftId:"draft-1",workspaceId:"workspace-1",attempt:2,plan:{}},store={claim:vi.fn().mockResolvedValue(job),deferRateLimit:vi.fn(),retry:vi.fn(),fail:vi.fn(),success:vi.fn()},publisher={publish:vi.fn().mockRejectedValue(new ShopifyGraphqlError([],429,4000))},logger={info:vi.fn(),error:vi.fn()},worker=new StorePublicationWorker(store as never,publisher as never,logger as never,{workerId:"worker",leaseSeconds:60,maxAttempts:4,pollMs:100});await expect(worker.processOne()).resolves.toBe(true);expect(store.deferRateLimit).toHaveBeenCalledWith("job-3","worker",4000);expect(store.retry).not.toHaveBeenCalled();expect(store.fail).not.toHaveBeenCalled();expect(logger.info).toHaveBeenCalledWith("shopify.store.rate-limited",expect.objectContaining({delayMs:4000}))});
});
