import{createHmac}from"node:crypto";import{describe,expect,it,vi}from"vitest";import{ShopifyTokenAlertDeliveryService,SignedShopifyTokenAlertWebhook}from"../src/integrations/shopify-token-alert-delivery.js";
const row={id:"delivery-1",workspace_id:"workspace-1",account_label:"store.myshopify.com",alert_kind:"REAUTH_REQUIRED"as const,occurrence_key:new Date("2026-08-12T00:00:00Z"),attempts:1,refresh_failure_count:0};
describe("Shopify token alert delivery",()=>{
  it("sends a secret-free signed HTTPS payload",async()=>{let sentBody="",headers=new Headers();const fetcher=vi.fn(async(_url:string|URL|Request,init?:RequestInit)=>{sentBody=String(init?.body);headers=new Headers(init?.headers);return new Response(null,{status:202})}),sender=new SignedShopifyTokenAlertWebhook("https://alerts.example/shopify","0123456789abcdef",fetcher as typeof fetch),payload={id:"delivery-1",workspaceId:"workspace-1",shopDomain:"store.myshopify.com",kind:"REAUTH_REQUIRED"as const,occurredAt:"2026-08-12T00:00:00.000Z",refreshFailureCount:0};await expect(sender.send(payload)).resolves.toEqual({status:202});const timestamp=headers.get("X-Storzy-Timestamp")!,expected=createHmac("sha256","0123456789abcdef").update(timestamp+"."+sentBody).digest("hex");expect(headers.get("X-Storzy-Signature")).toBe("sha256="+expected);expect(JSON.parse(sentBody)).toEqual(payload);expect(sentBody).not.toMatch(/accessToken|refreshToken|clientSecret/)});
  it("seeds idempotent incidents and marks successful delivery",async()=>{const query=vi.fn(async(sql:string)=>sql.startsWith("WITH candidates")?{rows:[row]}:{rows:[],rowCount:1}),sender={send:vi.fn().mockResolvedValue({status:204})},service=new ShopifyTokenAlertDeliveryService({query}as never,sender,{workerId:"worker-1",maxAttempts:6,leaseSeconds:30});await expect(service.deliverBatch()).resolves.toEqual({claimed:1,sent:1,failed:0});const seed=String(query.mock.calls[0]?.[0]);expect(seed).toContain("ON CONFLICT(connection_id,alert_kind,occurrence_key) DO NOTHING");expect(seed).toContain("refreshFailureCount')::int,0)=3");expect(sender.send).toHaveBeenCalledWith({id:"delivery-1",workspaceId:"workspace-1",shopDomain:"store.myshopify.com",kind:"REAUTH_REQUIRED",occurredAt:"2026-08-12T00:00:00.000Z",refreshFailureCount:0});expect(query.mock.calls.some(call=>String(call[0]).includes("status='SENT'"))).toBe(true)});
  it("records bounded failure and exponential retry",async()=>{const failedRow={...row,attempts:3,alert_kind:"REFRESH_REPEATED_FAILURE"as const,refresh_failure_count:3},query=vi.fn(async(sql:string,_params?:unknown[])=>sql.startsWith("WITH candidates")?{rows:[failedRow]}:{rows:[],rowCount:1}),sender={send:vi.fn().mockRejectedValue(Object.assign(new Error("webhook unavailable"),{status:503}))},service=new ShopifyTokenAlertDeliveryService({query}as never,sender,{workerId:"worker-1",maxAttempts:6,leaseSeconds:30});await expect(service.deliverBatch()).resolves.toEqual({claimed:1,sent:0,failed:1});const failed=query.mock.calls.find(call=>String(call[0]).includes("status='FAILED'"));expect(failed?.[1]).toEqual(["delivery-1","worker-1",503,"webhook unavailable",120])});
  it("requires HTTPS and a sufficiently long signing secret",()=>{expect(()=>new SignedShopifyTokenAlertWebhook("http://alerts.example","0123456789abcdef")).toThrow("must use HTTPS");expect(()=>new SignedShopifyTokenAlertWebhook("https://alerts.example","short")).toThrow("at least 16")});
  it("lists only workspace deliveries and requeues a failed delivery with a fresh retry budget and audit action",async()=>{const listQuery=vi.fn().mockResolvedValue({rows:[{id:"delivery-1",status:"FAILED"}]}),listing=new ShopifyTokenAlertDeliveryService({query:listQuery}as never);await expect(listing.list({workspaceId:"workspace-1",limit:25})).resolves.toHaveLength(1);expect(String(listQuery.mock.calls[0]?.[0])).toContain("d.workspace_id=$1");expect(listQuery.mock.calls[0]?.[1]).toEqual(["workspace-1",25]);const calls:string[]=[],query=vi.fn(async(sql:string)=>{calls.push(sql);if(sql.startsWith("SELECT status"))return{rows:[{status:"FAILED",attempts:6}]};if(sql.startsWith("UPDATE shopify_token_alert_deliveries"))return{rows:[{id:"delivery-1",status:"PENDING",attempts:0}]};return{rows:[]}}),client={query,release:vi.fn()},service=new ShopifyTokenAlertDeliveryService({connect:vi.fn(async()=>client)}as never);await expect(service.requeue({workspaceId:"workspace-1",id:"delivery-1",actorId:"operator",reason:"운영 채널 복구"})).resolves.toMatchObject({status:"PENDING",attempts:0});expect(calls.some(sql=>sql.includes("status='PENDING',attempts=0"))).toBe(true);expect(calls.some(sql=>sql.includes("before_attempts"))).toBe(true);expect(query).toHaveBeenCalledWith("COMMIT")});
});
