import {afterEach,describe,expect,it,vi} from "vitest";
import {ShopifyConnectionUnavailableError,WorkspaceShopifyPublisher} from "../src/shopify/workspace-publisher.js";
import {ShopifyPublicationWorker} from "../src/shopify/worker.js";

afterEach(()=>vi.unstubAllGlobals());
const payload={identifier:{handle:"storzy-1"},input:{title:"Seoul Tee"}};

describe("workspace Shopify publisher",()=>{
  it("워크스페이스에 암호화 저장된 연결로 상품을 게시한다",async()=>{const fetch=vi.fn(async(_input:string|URL|Request,_init?:RequestInit)=>new Response(JSON.stringify({data:{productSet:{product:{id:"gid://shopify/Product/1"},userErrors:[]}}}),{status:200,headers:{"Content-Type":"application/json"}}));vi.stubGlobal("fetch",fetch);const connections={list:vi.fn().mockResolvedValue([{provider:"SHOPIFY",status:"CONNECTED",accountLabel:"seoul.myshopify.com"}]),credentials:vi.fn().mockResolvedValue({accessToken:"workspace-token"})},publisher=new WorkspaceShopifyPublisher(connections as never,"2026-07");await expect(publisher.publish(payload,"workspace-1")).resolves.toMatchObject({productId:"gid://shopify/Product/1"});expect(String(fetch.mock.calls[0]?.[0])).toContain("seoul.myshopify.com/admin/api/2026-07/graphql.json");expect(fetch.mock.calls[0]?.[1]?.headers).toMatchObject({"X-Shopify-Access-Token":"workspace-token"})});
  it("연결이 없으면 명시적인 대기 오류를 반환한다",async()=>{const connections={list:vi.fn().mockResolvedValue([]),credentials:vi.fn().mockResolvedValue(null)},publisher=new WorkspaceShopifyPublisher(connections as never,"2026-07");await expect(publisher.publish(payload,"workspace-1")).rejects.toBeInstanceOf(ShopifyConnectionUnavailableError)});
  it("재인증이 필요한 workspace 요청을 환경변수 fallback 스토어로 보내지 않는다",async()=>{const accessProvider={resolve:vi.fn().mockResolvedValue(null)},publisher=new WorkspaceShopifyPublisher(undefined,"2026-07",{shopDomain:"fallback.myshopify.com",accessToken:"fallback-token"},accessProvider);await expect(publisher.publish(payload,"workspace-1")).rejects.toBeInstanceOf(ShopifyConnectionUnavailableError)});
  it("연결 대기 작업은 시도 횟수를 소모하지 않도록 defer한다",async()=>{const store={claim:vi.fn().mockResolvedValue({id:"job-1",revisionId:"revision-1",workspaceId:"workspace-1",attempt:1}),extend:vi.fn(),payload:vi.fn().mockResolvedValue(payload),deferConnection:vi.fn().mockResolvedValue(true),success:vi.fn(),retry:vi.fn(),fail:vi.fn()},publisher={publish:vi.fn().mockRejectedValue(new ShopifyConnectionUnavailableError())},logger={child:vi.fn(),debug:vi.fn(),info:vi.fn(),warn:vi.fn(),error:vi.fn()},worker=new ShopifyPublicationWorker(store as never,publisher,logger as never,{workerId:"worker",leaseSeconds:30,maxAttempts:4,pollMs:10});await expect(worker.processOne()).resolves.toBe(true);expect(store.deferConnection).toHaveBeenCalledWith("job-1","worker");expect(store.retry).not.toHaveBeenCalled();expect(store.fail).not.toHaveBeenCalled()});
});
