import {afterEach,describe,expect,it,vi} from "vitest";
import {WorkspacePrintfulOrderClients} from "../src/orders/workspace-printful-client.js";
import {PrintfulOrderConnectionUnavailableError,PrintfulOrderWorker} from "../src/orders/printful-worker.js";
afterEach(()=>vi.unstubAllGlobals());
describe("workspace Printful order",()=>{
  it("uses workspace token and store ID",async()=>{const fetch=vi.fn(async(_input:string|URL|Request,_init?:RequestInit)=>new Response(JSON.stringify({result:{id:99,status:"draft"}}),{status:200,headers:{"Content-Type":"application/json"}}));vi.stubGlobal("fetch",fetch);const connections={list:vi.fn().mockResolvedValue([{provider:"PRINTFUL",status:"CONNECTED",accountLabel:"42"}]),credentials:vi.fn().mockResolvedValue({token:"workspace-token",storeId:"42"})},resolver=new WorkspacePrintfulOrderClients(connections as never,"https://api.printful.com");await (await resolver.forWorkspace("workspace-1")).getOrder("99");const headers=new Headers(fetch.mock.calls[0]?.[1]?.headers);expect(headers.get("Authorization")).toBe("Bearer workspace-token");expect(headers.get("X-PF-Store-Id")).toBe("42")});
  it("reports an unavailable workspace connection",async()=>{const resolver=new WorkspacePrintfulOrderClients({list:vi.fn().mockResolvedValue([]),credentials:vi.fn().mockResolvedValue(null)} as never,"https://api.printful.com");await expect(resolver.forWorkspace("workspace-1")).rejects.toBeInstanceOf(PrintfulOrderConnectionUnavailableError)});
  it("defers without consuming the order when Printful disconnects",async()=>{const job={id:"job-1",orderId:"order-1",workspaceId:"workspace-1",externalId:"storzy-order",phase:"PENDING_DRAFT" as const,remoteOrderId:null,attempt:1},store={claim:vi.fn().mockResolvedValue(job),automationEnabled:vi.fn().mockResolvedValue(true),deferConnection:vi.fn(),hold:vi.fn(),retry:vi.fn()},resolver={forWorkspace:vi.fn().mockRejectedValue(new PrintfulOrderConnectionUnavailableError())},worker=new PrintfulOrderWorker(store as never,resolver,"worker");await expect(worker.tick()).resolves.toBe(true);expect(store.deferConnection).toHaveBeenCalledWith(job,"worker");expect(store.hold).not.toHaveBeenCalled();expect(store.retry).not.toHaveBeenCalled()});
});
