import{performance}from"node:perf_hooks";import{ShopifyAdminClient}from"./shopify.js";import{PrintfulClient}from"./printful.js";
export type ProviderSmokeCheck=Readonly<{provider:"SHOPIFY"|"PRINTFUL";key:string;ok:boolean;message:string;latencyMs:number}>;
const requiredScopes=["write_products","write_content","read_orders"];
const timed=(fetcher:typeof fetch,timeoutMs:number):typeof fetch=>(input,init={})=>fetcher(input,{...init,signal:AbortSignal.timeout(timeoutMs)});
export async function runProviderReadonlySmoke(env:NodeJS.ProcessEnv,fetcher:typeof fetch=fetch):Promise<Readonly<{ok:boolean;checks:ProviderSmokeCheck[]}>>{const checks:ProviderSmokeCheck[]=[],push=(provider:ProviderSmokeCheck["provider"],key:string,started:number,ok:boolean,message:string)=>checks.push({provider,key,ok,message,latencyMs:Math.max(0,Math.round(performance.now()-started))}),safeFetch=timed(fetcher,Number(env.PROVIDER_SMOKE_TIMEOUT_MS??"10000"));
  const shopDomain=env.SHOPIFY_SHOP_DOMAIN?.trim(),shopifyToken=env.SHOPIFY_ADMIN_ACCESS_TOKEN?.trim(),shopifyStart=performance.now();
  if(!shopDomain||!shopifyToken)push("SHOPIFY","CONFIG",shopifyStart,false,"SHOPIFY_SHOP_DOMAIN과 SHOPIFY_ADMIN_ACCESS_TOKEN이 필요합니다.");else try{const client=new ShopifyAdminClient({shopDomain,accessToken:shopifyToken,apiVersion:env.SHOPIFY_API_VERSION?.trim()||"2026-07",fetch:safeFetch}),data=await client.graphql<{shop:{name:string;myshopifyDomain:string;currencyCode:string};currentAppInstallation:{accessScopes:Array<{handle:string}>};products:{nodes:Array<{id:string;title:string;status:string}>}}>("query StorzyReadonlySmoke { shop { name myshopifyDomain currencyCode } currentAppInstallation { accessScopes { handle } } products(first: 1) { nodes { id title status } } }");push("SHOPIFY","ADMIN_GRAPHQL",shopifyStart,true,`${data.shop.name} · ${data.shop.myshopifyDomain} · ${data.shop.currencyCode}`);const granted=new Set(data.currentAppInstallation.accessScopes.map(item=>item.handle)),missing=requiredScopes.filter(scope=>!granted.has(scope));push("SHOPIFY","ACCESS_SCOPES",shopifyStart,missing.length===0,missing.length?`누락 scope: ${missing.join(", ")}`:`필수 scope ${requiredScopes.length}개 승인됨`);push("SHOPIFY","PRODUCT_READ",shopifyStart,true,`상품 읽기 성공 · 표본 ${data.products.nodes.length}개`);}catch(error){push("SHOPIFY","ADMIN_GRAPHQL",shopifyStart,false,error instanceof Error?error.message:"Shopify 조회 실패");}
  const printfulToken=env.PRINTFUL_TOKEN?.trim(),storeId=env.PRINTFUL_STORE_ID?.trim(),printfulStart=performance.now();
  if(!printfulToken||!storeId)push("PRINTFUL","CONFIG",printfulStart,false,"PRINTFUL_TOKEN과 PRINTFUL_STORE_ID가 필요합니다.");else try{const client=new PrintfulClient({token:printfulToken,storeId,baseUrl:env.PRINTFUL_API_BASE_URL?.trim()||"https://api.printful.com",fetch:safeFetch}),[store,catalog]=await Promise.all([client.request<{result?:{id?:number|string;name?:string}}>(`/stores/${encodeURIComponent(storeId)}`),client.listCatalogProducts(1,0)]);if(!store.result)throw new Error("Printful store 응답이 비어 있습니다.");push("PRINTFUL","STORE_READ",printfulStart,true,`${store.result.name||"Printful Store"} · ${store.result.id||storeId}`);push("PRINTFUL","CATALOG_V2_READ",printfulStart,Boolean(catalog),"Printful v2 카탈로그 표본 조회 성공");}catch(error){push("PRINTFUL","STORE_READ",printfulStart,false,error instanceof Error?error.message:"Printful 조회 실패");}
  return{ok:checks.length>=5&&checks.every(check=>check.ok),checks};}
