import{createHmac,randomUUID}from"node:crypto";import type pg from"pg";import{DomainError}from"../brand/errors.js";

export type ShopifyTokenAlertPayload=Readonly<{id:string;workspaceId:string;shopDomain:string;kind:"REAUTH_REQUIRED"|"REFRESH_REPEATED_FAILURE";occurredAt:string;refreshFailureCount:number}>;
export interface ShopifyTokenAlertSender{send(payload:ShopifyTokenAlertPayload):Promise<{status:number}>}

export class SignedShopifyTokenAlertWebhook implements ShopifyTokenAlertSender{
  private readonly url:URL;
  constructor(url:string,private readonly secret:string,private readonly fetcher:typeof fetch=fetch){this.url=new URL(url);if(this.url.protocol!=="https:")throw new Error("SHOPIFY_TOKEN_ALERT_WEBHOOK_URL must use HTTPS");if(secret.length<16)throw new Error("SHOPIFY_TOKEN_ALERT_WEBHOOK_SECRET must be at least 16 characters");}
  async send(payload:ShopifyTokenAlertPayload){const body=JSON.stringify(payload),timestamp=Math.floor(Date.now()/1000).toString(),signature=createHmac("sha256",this.secret).update(timestamp+"."+body).digest("hex"),response=await this.fetcher(this.url,{method:"POST",headers:{"Content-Type":"application/json","X-Storzy-Timestamp":timestamp,"X-Storzy-Signature":"sha256="+signature},body,signal:AbortSignal.timeout(10_000)});if(!response.ok)throw Object.assign(new Error(`Shopify token alert webhook returned ${response.status}`),{status:response.status});return{status:response.status};}
}

type Claimed={id:string;workspace_id:string;account_label:string;alert_kind:ShopifyTokenAlertPayload["kind"];occurrence_key:Date;attempts:number;refresh_failure_count:number};
export class ShopifyTokenAlertDeliveryService{
  constructor(private readonly pool:pg.Pool,private readonly sender?:ShopifyTokenAlertSender,private readonly options:{workerId:string;maxAttempts:number;leaseSeconds:number}={workerId:"shopify-token-alert-delivery",maxAttempts:6,leaseSeconds:30}){}
  async list(input:{workspaceId:string;limit?:number}){const limit=Math.min(Math.max(input.limit??50,1),100),found=await this.pool.query(`SELECT d.id,d.alert_kind,d.occurrence_key,d.status,d.attempts,d.response_status,d.last_error,d.sent_at,d.created_at,c.account_label shop_domain FROM shopify_token_alert_deliveries d JOIN integration_connections c ON c.id=d.connection_id WHERE d.workspace_id=$1 ORDER BY d.created_at DESC LIMIT $2`,[input.workspaceId,limit]);return found.rows;}
  async requeue(input:{workspaceId:string;id:string;actorId:string;reason:string}){const actorId=input.actorId.trim(),reason=input.reason.trim();if(!actorId||reason.length<1||reason.length>500)throw new DomainError("INVALID_INPUT","처리자와 1~500자의 재시도 사유가 필요합니다.");const client=await this.pool.connect();try{await client.query("BEGIN");const found=await client.query<{status:string;attempts:number}>("SELECT status,attempts FROM shopify_token_alert_deliveries WHERE id=$1 AND workspace_id=$2 FOR UPDATE",[input.id,input.workspaceId]),row=found.rows[0];if(!row){await client.query("ROLLBACK");return null;}if(row.status!=="FAILED")throw new DomainError("ALERT_DELIVERY_NOT_FAILED","실패한 알림 전송만 다시 시도할 수 있습니다.");const saved=await client.query("UPDATE shopify_token_alert_deliveries SET status='PENDING',attempts=0,available_at=now(),locked_by=NULL,lease_expires_at=NULL,response_status=NULL,last_error=NULL WHERE id=$1 RETURNING id,status,attempts,available_at",[input.id]);await client.query("INSERT INTO shopify_token_alert_delivery_actions(id,delivery_id,action,actor_id,reason,before_status,after_status,before_attempts) VALUES($1,$2,'REQUEUE',$3,$4,$5,'PENDING',$6)",[randomUUID(),input.id,actorId,reason,row.status,row.attempts]);await client.query("COMMIT");return saved.rows[0]??null;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  async deliverBatch(limit=20){if(!this.sender)throw new Error("Shopify token alert sender is not configured");if(!Number.isInteger(limit)||limit<1||limit>100)throw new Error("limit must be between 1 and 100");await this.pool.query(`INSERT INTO shopify_token_alert_deliveries(id,connection_id,workspace_id,alert_kind,occurrence_key)
SELECT gen_random_uuid(),id,workspace_id,'REAUTH_REQUIRED',COALESCE((metadata->>'reauthRequiredAt')::timestamptz,updated_at) FROM integration_connections WHERE provider='SHOPIFY' AND status='REAUTH_REQUIRED'
UNION ALL SELECT gen_random_uuid(),id,workspace_id,'REFRESH_REPEATED_FAILURE',(metadata->>'lastRefreshFailureAt')::timestamptz FROM integration_connections WHERE provider='SHOPIFY' AND status='CONNECTED' AND COALESCE((metadata->>'refreshFailureCount')::int,0)=3 AND metadata ? 'lastRefreshFailureAt'
ON CONFLICT(connection_id,alert_kind,occurrence_key) DO NOTHING`);
    const claimed=await this.pool.query<Claimed>(`WITH candidates AS(SELECT d.id FROM shopify_token_alert_deliveries d WHERE d.status IN('PENDING','FAILED') AND d.available_at<=now() AND d.attempts<$3 ORDER BY d.available_at,d.created_at FOR UPDATE SKIP LOCKED LIMIT $1),updated AS(UPDATE shopify_token_alert_deliveries d SET status='RUNNING',attempts=d.attempts+1,locked_by=$2,lease_expires_at=now()+($4::text||' seconds')::interval,last_error=NULL FROM candidates c WHERE d.id=c.id RETURNING d.id,d.connection_id,d.workspace_id,d.alert_kind,d.occurrence_key,d.attempts) SELECT u.id,u.workspace_id,c.account_label,u.alert_kind,u.occurrence_key,u.attempts,COALESCE((c.metadata->>'refreshFailureCount')::int,0) refresh_failure_count FROM updated u JOIN integration_connections c ON c.id=u.connection_id`,[limit,this.options.workerId,this.options.maxAttempts,this.options.leaseSeconds]);let sent=0,failed=0;
    for(const row of claimed.rows){const payload:ShopifyTokenAlertPayload={id:row.id,workspaceId:row.workspace_id,shopDomain:row.account_label,kind:row.alert_kind,occurredAt:row.occurrence_key.toISOString(),refreshFailureCount:row.refresh_failure_count};try{const result=await this.sender.send(payload);await this.pool.query("UPDATE shopify_token_alert_deliveries SET status='SENT',response_status=$3,sent_at=now(),locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND locked_by=$2",[row.id,this.options.workerId,result.status]);sent++;}catch(error){const status=typeof(error as{status?:unknown}).status==="number"?(error as{status:number}).status:null,message=error instanceof Error?error.message:String(error),delay=Math.min(3600,30*2**Math.max(0,row.attempts-1));await this.pool.query("UPDATE shopify_token_alert_deliveries SET status='FAILED',response_status=$3,last_error=$4,available_at=now()+($5::text||' seconds')::interval,locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND locked_by=$2",[row.id,this.options.workerId,status,message.slice(0,1000),delay]);failed++;}}
    return{claimed:claimed.rows.length,sent,failed};
  }
}
