import type pg from"pg";import{productionProcesses}from"../deployment/production-templates.js";
export type ProcessKind="service"|"worker"|"scheduler";
export class ProcessHeartbeatStore{
  constructor(private readonly pool:pg.Pool,private readonly expectedRelease=process.env.STORZY_RELEASE?.trim()||"development"){}
  async start(role:string,instanceId:string,type:ProcessKind){await this.pool.query("INSERT INTO process_heartbeats(role,instance_id,process_type,status,release) VALUES($1,$2,$3,'RUNNING',$4) ON CONFLICT(role,instance_id) DO UPDATE SET process_type=$3,status='RUNNING',release=$4,started_at=now(),heartbeat_at=now(),completed_at=NULL,last_error=NULL",[role,instanceId,type,this.expectedRelease]);}
  async beat(role:string,instanceId:string){await this.pool.query("UPDATE process_heartbeats SET heartbeat_at=now(),release=$3 WHERE role=$1 AND instance_id=$2 AND status='RUNNING'",[role,instanceId,this.expectedRelease]);}
  async finish(role:string,instanceId:string,status:"SUCCEEDED"|"FAILED"|"STOPPED",error?:string){await this.pool.query("UPDATE process_heartbeats SET status=$3,heartbeat_at=now(),completed_at=now(),last_error=$4,release=$5 WHERE role=$1 AND instance_id=$2",[role,instanceId,status,error?.replace(/[\r\n\t]+/g," ").slice(0,500)??null,this.expectedRelease]);}
  async health(now=new Date()){const found=await this.pool.query<{role:string;process_type:ProcessKind;status:string;release:string;started_at:Date;heartbeat_at:Date;completed_at:Date|null;last_error:string|null}>("SELECT DISTINCT ON(role) role,process_type,status,release,started_at,heartbeat_at,completed_at,last_error FROM process_heartbeats ORDER BY role,heartbeat_at DESC"),latest=new Map(found.rows.map(row=>[row.role,row])),expected=productionProcesses().processes,items=expected.map(item=>{const row=latest.get(item.name),age=row?now.getTime()-row.heartbeat_at.getTime():Infinity,maxAge=item.type==="scheduler"&&"schedule"in item?(item.schedule.startsWith("*/5")?15:150)*60_000:90_000,state=!row?"NEVER_SEEN":row.status==="FAILED"?"FAILED":row.release!==this.expectedRelease?"RELEASE_MISMATCH":age>maxAge?"STALE":"HEALTHY";return{role:item.name,type:item.type,state,status:row?.status??null,release:row?.release??null,expectedRelease:this.expectedRelease,lastHeartbeatAt:row?.heartbeat_at.toISOString()??null,lastError:row?.last_error??null}}),count=(state:string)=>items.filter(item=>item.state===state).length;return{healthy:items.every(item=>item.state==="HEALTHY"),summary:{healthy:count("HEALTHY"),stale:count("STALE"),failed:count("FAILED"),releaseMismatch:count("RELEASE_MISMATCH"),neverSeen:count("NEVER_SEEN"),total:items.length},items};}
}
