import {randomUUID} from "node:crypto";
import type pg from "pg";

export type OrderAutomationControl=Readonly<{workspaceId:string;enabled:boolean;approvedBy:string|null;approvedAt:string|null;reason:string|null;updatedAt:string|null}>;
export type OrderAutomationAction=Readonly<{id:string;action:"ENABLE"|"DISABLE";actorId:string;reason:string;createdAt:string}>;
export type OrderAutomationActivity=Readonly<{running:number;heldRemoteDrafts:number;queued:number;rateLimitedWaiting:number;rateLimitUsed:number;rateLimitCapacity:number;rateLimitResetsAt:string|null;requiresAttention:boolean}>;
export interface OrderAutomationGate{isEnabled(workspaceId:string,client?:pg.PoolClient):Promise<boolean>}

export class OrderAutomationControlService implements OrderAutomationGate{
  constructor(private readonly pool:pg.Pool,private readonly printfulRateLimitCapacity=2){}
  async isEnabled(workspaceId:string,client?:pg.PoolClient):Promise<boolean>{const result=await (client??this.pool).query<{enabled:boolean}>("SELECT enabled FROM workspace_order_automation_controls WHERE workspace_id=$1",[workspaceId]);return result.rows[0]?.enabled===true}
  async get(workspaceId:string):Promise<OrderAutomationControl>{const result=await this.pool.query<{workspace_id:string;enabled:boolean;approved_by:string|null;approved_at:Date|null;reason:string;updated_at:Date}>("SELECT workspace_id,enabled,approved_by,approved_at,reason,updated_at FROM workspace_order_automation_controls WHERE workspace_id=$1",[workspaceId]),row=result.rows[0];return row?{workspaceId:row.workspace_id,enabled:row.enabled,approvedBy:row.approved_by,approvedAt:row.approved_at?.toISOString()??null,reason:row.reason,updatedAt:row.updated_at.toISOString()}:{workspaceId,enabled:false,approvedBy:null,approvedAt:null,reason:null,updatedAt:null}}
  async history(workspaceId:string,limit=20):Promise<OrderAutomationAction[]>{const bounded=Math.min(50,Math.max(1,Math.trunc(limit)||20)),result=await this.pool.query<{id:string;action:"ENABLE"|"DISABLE";actor_id:string;reason:string;created_at:Date}>("SELECT id,action,actor_id,reason,created_at FROM workspace_order_automation_actions WHERE workspace_id=$1 ORDER BY created_at DESC,id DESC LIMIT $2",[workspaceId,bounded]);return result.rows.map(row=>({id:row.id,action:row.action,actorId:row.actor_id,reason:row.reason,createdAt:row.created_at.toISOString()}))}
  async activity(workspaceId:string):Promise<OrderAutomationActivity>{const result=await this.pool.query<{running:string;held_remote_drafts:string;queued:string;rate_limited_waiting:string;rate_limit_used:number|null;rate_limit_resets_at:Date|null}>(`SELECT count(*) FILTER(WHERE j.status='RUNNING')::text running,count(*) FILTER(WHERE j.status='HELD' AND j.remote_order_id IS NOT NULL AND j.confirmed_response IS NULL)::text held_remote_drafts,count(*) FILTER(WHERE j.status IN('PENDING_DRAFT','WAITING_COST','READY_CONFIRM'))::text queued,count(*) FILTER(WHERE j.status IN('PENDING_DRAFT','WAITING_COST','READY_CONFIRM') AND j.last_error='WAITING_FOR_PRINTFUL_RATE_LIMIT')::text rate_limited_waiting,(SELECT CASE WHEN r.window_started_at+interval '1 minute'>now() THEN r.used ELSE 0 END FROM workspace_printful_order_rate_limits r WHERE r.workspace_id=$1) rate_limit_used,(SELECT CASE WHEN r.window_started_at+interval '1 minute'>now() THEN r.window_started_at+interval '1 minute' END FROM workspace_printful_order_rate_limits r WHERE r.workspace_id=$1) rate_limit_resets_at FROM printful_order_jobs j WHERE j.workspace_id=$1`,[workspaceId]),row=result.rows[0],running=Number(row?.running??0),heldRemoteDrafts=Number(row?.held_remote_drafts??0),queued=Number(row?.queued??0),rateLimitedWaiting=Number(row?.rate_limited_waiting??0);return{running,heldRemoteDrafts,queued,rateLimitedWaiting,rateLimitUsed:Number(row?.rate_limit_used??0),rateLimitCapacity:this.printfulRateLimitCapacity,rateLimitResetsAt:row?.rate_limit_resets_at?.toISOString()??null,requiresAttention:running+heldRemoteDrafts>0}}
  async set(input:Readonly<{workspaceId:string;enabled:boolean;actorId:string;reason:string}>):Promise<OrderAutomationControl>{const actorId=input.actorId.trim(),reason=input.reason.trim();if(!actorId||!reason)throw Object.assign(new Error("담당자와 전환 사유가 필요합니다."),{status:400});const client=await this.pool.connect();try{await client.query("BEGIN");await client.query(`INSERT INTO workspace_order_automation_controls(workspace_id,enabled,approved_by,approved_at,reason) VALUES($1,$2,$3,CASE WHEN $2 THEN now() ELSE NULL END,$4) ON CONFLICT(workspace_id) DO UPDATE SET enabled=EXCLUDED.enabled,approved_by=EXCLUDED.approved_by,approved_at=EXCLUDED.approved_at,reason=EXCLUDED.reason,updated_at=now()`,[input.workspaceId,input.enabled,input.enabled?actorId:null,reason]);await client.query("INSERT INTO workspace_order_automation_actions(id,workspace_id,action,actor_id,reason) VALUES($1,$2,$3,$4,$5)",[randomUUID(),input.workspaceId,input.enabled?"ENABLE":"DISABLE",actorId,reason]);await client.query("COMMIT")}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}return this.get(input.workspaceId)}
}
