import{randomUUID}from"node:crypto";
import type pg from"pg";
import{money}from"../domain/money.js";
import{evaluateOrder,type OrderPolicy}from"../domain/order-policy.js";
import{DomainError}from"../brand/errors.js";
type Status="READY"|"WAITING"|"HELD"|"REJECTED"|"ALREADY_PROCESSED"|"SUBMITTED";
type Action="REVALIDATE"|"MANUAL_APPROVE"|"REJECT";

export class OrderExceptionService{
  constructor(private readonly pool:pg.Pool,private readonly allowedCountries:ReadonlySet<string>,private readonly policy:OrderPolicy){}
  async requeueFulfillment(input:Readonly<{workspaceId:string;orderId:string;actorId:string;reason:string;idempotencyKey:string}>){const actorId=input.actorId.trim(),reason=input.reason.trim();if(!actorId||reason.length<1||reason.length>500)throw new DomainError("INVALID_INPUT","담당자와 1~500자의 재시도 사유가 필요합니다.");const client=await this.pool.connect();try{await client.query('BEGIN');const order=await client.query<{id:string}>(`SELECT id FROM commerce_orders WHERE id=$1 AND workspace_id=$2 FOR UPDATE`,[input.orderId,input.workspaceId]);if(!order.rows[0]){await client.query('ROLLBACK');return null}const prior=await client.query<{shopify_fulfillment_job_id:string}>(`SELECT shopify_fulfillment_job_id FROM shopify_fulfillment_requeue_actions WHERE workspace_id=$1 AND idempotency_key=$2`,[input.workspaceId,input.idempotencyKey]);if(prior.rows[0]){await client.query('COMMIT');return{jobId:prior.rows[0].shopify_fulfillment_job_id,duplicate:true}}const failed=await client.query<{id:string;attempts:number}>(`SELECT j.id,j.attempts FROM shopify_fulfillment_jobs j JOIN fulfillment_shipments s ON s.id=j.shipment_id WHERE s.commerce_order_id=$1 AND j.status='FAILED' ORDER BY j.finished_at DESC NULLS LAST,j.created_at DESC FOR UPDATE OF j LIMIT 1`,[input.orderId]),job=failed.rows[0];if(!job)throw new DomainError("FULFILLMENT_NOT_REQUEUEABLE","재시도할 실패 배송 작업이 없습니다.");await client.query(`UPDATE shopify_fulfillment_jobs SET status='PENDING',attempts=0,available_at=now(),last_error=NULL,finished_at=NULL,locked_by=NULL,lease_expires_at=NULL WHERE id=$1`,[job.id]);await client.query(`INSERT INTO shopify_fulfillment_requeue_actions(id,workspace_id,commerce_order_id,shopify_fulfillment_job_id,actor_id,reason,idempotency_key,before_attempts)VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[randomUUID(),input.workspaceId,input.orderId,job.id,actorId,reason,input.idempotencyKey,job.attempts]);await client.query('COMMIT');return{jobId:job.id,duplicate:false}}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
  async list(input:Readonly<{workspaceId:string;status?:"HELD"|"WAITING"|"RETURNED"|"SUBMITTED"|"FULFILLMENT_FAILED";limit:number;offset:number}>){const values:unknown[]=[input.workspaceId],where=[`workspace_id=$1`,input.status?`true`:`status IN ('HELD','WAITING','RETURNED')`];if(input.status==='FULFILLMENT_FAILED')where.push(`EXISTS(SELECT 1 FROM fulfillment_shipments fs JOIN shopify_fulfillment_jobs fj ON fj.shipment_id=fs.id WHERE fs.commerce_order_id=commerce_orders.id AND fj.status='FAILED')`);else if(input.status){values.push(input.status);where.push(`status=$${values.length}`)}values.push(input.limit,input.offset);return(await this.pool.query(`SELECT id,shopify_order_id,order_name,currency,revenue_minor,current_variable_cost_minor,shipping_country,item_count,financial_status,status,decision_reasons,margin_basis_points,created_at,updated_at FROM commerce_orders WHERE ${where.join(" AND ")} ORDER BY created_at DESC,id DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values)).rows}
  async detail(workspaceId:string,id:string){const order=await this.pool.query(`SELECT * FROM commerce_orders WHERE id=$1 AND workspace_id=$2`,[id,workspaceId]);if(!order.rows[0])return null;const[lines,actions,shipments,jobs,printfulEvents,fulfillmentEvents,fulfillmentJobs,fulfillmentRequeueActions]=await Promise.all([this.pool.query(`SELECT * FROM commerce_order_lines WHERE commerce_order_id=$1 ORDER BY shopify_line_item_id`,[id]),this.pool.query(`SELECT * FROM order_exception_actions WHERE commerce_order_id=$1 ORDER BY created_at DESC`,[id]),this.pool.query(`SELECT * FROM fulfillment_shipments WHERE commerce_order_id=$1 ORDER BY created_at`,[id]),this.pool.query(`SELECT id,status,remote_order_id,confirmed_response,quoted_cost_minor,quoted_currency,last_error,attempts FROM printful_order_jobs WHERE commerce_order_id=$1`,[id]),this.pool.query(`SELECT event_type,actor_id,remote_order_id,detail,created_at FROM printful_order_job_events WHERE workspace_id=$1 AND commerce_order_id=$2 ORDER BY created_at DESC`,[workspaceId,id]),this.pool.query(`SELECT e.event_type,e.actor_id,e.shopify_fulfillment_id,e.detail,e.created_at FROM shopify_fulfillment_job_events e JOIN fulfillment_shipments s ON s.id=e.shipment_id WHERE e.workspace_id=$1 AND s.commerce_order_id=$2 ORDER BY e.created_at DESC`,[workspaceId,id]),this.pool.query(`SELECT j.id,j.status,j.attempts,j.last_error,j.shopify_fulfillment_id,j.finished_at,s.tracking_number FROM shopify_fulfillment_jobs j JOIN fulfillment_shipments s ON s.id=j.shipment_id WHERE s.commerce_order_id=$1 ORDER BY j.created_at DESC`,[id]),this.pool.query(`SELECT actor_id,reason,before_attempts,created_at FROM shopify_fulfillment_requeue_actions WHERE workspace_id=$1 AND commerce_order_id=$2 ORDER BY created_at DESC`,[workspaceId,id])]);return{order:order.rows[0],lines:lines.rows,actions:actions.rows,shipments:shipments.rows,printfulJob:jobs.rows[0]??null,printfulEvents:printfulEvents.rows,fulfillmentEvents:fulfillmentEvents.rows,fulfillmentJobs:fulfillmentJobs.rows,fulfillmentRequeueActions:fulfillmentRequeueActions.rows}}
  async act(input:Readonly<{workspaceId:string;orderId:string;action:Action;actorId:string;reason?:string;idempotencyKey:string}>){const client=await this.pool.connect();try{
    await client.query("BEGIN");
    const selected=await client.query<{id:string;shopify_order_id:string;currency:string;revenue_minor:string;approved_variable_cost_minor:string;current_variable_cost_minor:string;shipping_country:string;item_count:number;financial_status:string;status:Status;decision_reasons:string[]}>(`SELECT id,shopify_order_id,currency,revenue_minor,approved_variable_cost_minor,current_variable_cost_minor,shipping_country,item_count,financial_status,status,decision_reasons FROM commerce_orders WHERE id=$1 AND workspace_id=$2 FOR UPDATE`,[input.orderId,input.workspaceId]),row=selected.rows[0];
    if(!row){await client.query("ROLLBACK");return null}
    const prior=await client.query<{after_status:Status;after_reasons:string[]}>(`SELECT after_status,after_reasons FROM order_exception_actions WHERE commerce_order_id=$1 AND idempotency_key=$2`,[row.id,input.idempotencyKey]);if(prior.rows[0]){await client.query("COMMIT");return{status:prior.rows[0].after_status,reasons:prior.rows[0].after_reasons,duplicate:true}}
    if(!["HELD","WAITING"].includes(row.status))throw new DomainError("ORDER_NOT_ACTIONABLE","Only held or waiting orders can be actioned");if(input.action!=="REVALIDATE"&&!input.reason?.trim())throw new DomainError("INVALID_INPUT","reason is required");
    const reconciliationReview=row.decision_reasons.some(reason=>reason==="RECONCILIATION_REPLAY_REVIEW"||reason==="FINANCIAL_STATUS_SYNC_REVIEW");if(input.action==="MANUAL_APPROVE"&&reconciliationReview)throw new DomainError("ORDER_NOT_ACTIONABLE","대조 복구 주문은 수동 승인할 수 없습니다. 정책 재검증을 실행해 주세요.");
    let status:Status,reasons:string[];
    if(input.action==="MANUAL_APPROVE"){status="READY";reasons=[]}
    else if(input.action==="REJECT"){status="REJECTED";reasons=[...row.decision_reasons,"MANUALLY_REJECTED"]}
    else{const raw=await client.query<{payload:Record<string,unknown>}>(`SELECT wr.payload FROM shopify_order_webhook_receipts wr JOIN commerce_orders o ON o.source_webhook_id=wr.id WHERE o.id=$1`,[row.id]),address=(raw.rows[0]?.payload.shipping_address??{})as Record<string,unknown>,lines=await client.query<{mapping_count:number;design_present:boolean;quantity:number}>(`SELECT mapping_count,design_present,quantity FROM commerce_order_lines WHERE commerce_order_id=$1`,[row.id]),decision=evaluateOrder({revenue:money(BigInt(row.revenue_minor),row.currency),currentVariableCost:money(BigInt(row.current_variable_cost_minor),row.currency),approvedVariableCost:money(BigInt(row.approved_variable_cost_minor),row.currency),shippingCountry:row.shipping_country,allowedCountries:this.allowedCountries,addressValid:!!String(address.name??"").trim()&&!!String(address.address1??"").trim()&&!!String(address.city??"").trim()&&!!String(address.zip??"").trim(),variantAvailable:lines.rows.every(x=>x.mapping_count===1),designPresent:lines.rows.every(x=>x.design_present),mappingCount:lines.rows.every(x=>x.mapping_count===1)?1:0,paymentReady:["paid","partially_refunded"].includes(row.financial_status),alreadySubmitted:false,itemCount:row.item_count},this.policy);status=decision.status==="READY"?"READY":decision.status==="WAITING"?"WAITING":"HELD";reasons=[...decision.reasons]}
    if(status==="READY"){const automation=await client.query<{enabled:boolean}>(`SELECT enabled FROM workspace_order_automation_controls WHERE workspace_id=$1 FOR SHARE`,[input.workspaceId]);if(automation.rows[0]?.enabled!==true){status="HELD";reasons=["ORDER_AUTOMATION_SUSPENDED"]}}
    await client.query(`UPDATE commerce_orders SET status=$2,decision_reasons=$3::jsonb,updated_at=now() WHERE id=$1`,[row.id,status,JSON.stringify(reasons)]);
    if(status==="READY")await client.query(`INSERT INTO printful_order_jobs(id,commerce_order_id,workspace_id,external_id) VALUES($1,$2,$3,$4) ON CONFLICT(commerce_order_id) DO UPDATE SET status=CASE WHEN printful_order_jobs.status IN ('HELD','FAILED') AND printful_order_jobs.remote_order_id IS NULL THEN 'PENDING_DRAFT' ELSE printful_order_jobs.status END,available_at=now(),finished_at=NULL,last_error=NULL`,[randomUUID(),row.id,input.workspaceId,`storzy:${input.workspaceId}:${row.shopify_order_id}`]);
    if(status==="REJECTED")await client.query(`UPDATE printful_order_jobs SET status='HELD',last_error='MANUALLY_REJECTED',finished_at=now(),locked_by=NULL,lease_expires_at=NULL WHERE commerce_order_id=$1 AND status IN ('PENDING_DRAFT','WAITING_COST','READY_CONFIRM')`,[row.id]);
    await client.query(`INSERT INTO order_exception_actions(id,commerce_order_id,action,actor_id,reason,before_status,after_status,before_reasons,after_reasons,idempotency_key)VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10)`,[randomUUID(),row.id,input.action,input.actorId,input.reason?.trim()??null,row.status,status,JSON.stringify(row.decision_reasons),JSON.stringify(reasons),input.idempotencyKey]);await client.query("COMMIT");return{status,reasons,duplicate:false}
  }catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}
}
