const routes = [
  ["/admin", "운영 현황"], ["/admin/onboarding", "브랜드"], ["/admin/store", "스토어"],
  ["/admin/catalog", "상품"], ["/admin/designs", "디자인"], ["/admin/orders", "주문"],
  ["/admin/integrations", "연동 설정"],
  ["/admin/privacy", "개인정보"], ["/admin/security", "로그인 보안"],
] as const;

export function decorateAdminHtml(html: string, pathname: string): string {
  const navigation = routes.map(([href, label]) => `<a href="${href}"${pathname === href || (href === "/admin" && pathname === "/admin/") ? ' class="active" aria-current="page"' : ""}>${label}</a>`).join("");
  const automationActivity=pathname==="/admin"||pathname==="/admin/"||pathname==="/admin/integrations"||pathname==="/admin/orders";
  const securityAlertActivity=pathname==="/admin"||pathname==="/admin/";
  return html
    .replace("</head>", `<link rel="stylesheet" href="/admin/assets/system.css">${securityAlertActivity?'<link rel="stylesheet" href="/admin/assets/security-alerts.css">':''}${automationActivity?'<link rel="stylesheet" href="/admin/assets/order-automation-activity.css">':''}${pathname==="/admin"||pathname==="/admin/"?'<link rel="stylesheet" href="/admin/assets/overview-shopify-throttle.css"><link rel="stylesheet" href="/admin/assets/overview-uninstall-alert.css">':''}<script src="/admin/assets/auth-session.js" defer></script></head>`)
    .replace("<body>", `<body><nav class="app-nav" aria-label="주요 메뉴"><a class="app-brand" href="/admin"><span class="brand-mark">S</span><span>STORZY</span></a><div class="app-links">${navigation}</div><span class="environment"><i></i>MVP 워크스페이스</span></nav>`)
    .replace("</body>", `<script src="/admin/assets/i18n-ko.js" defer></script><script src="/admin/assets/shell.js" defer></script>${securityAlertActivity?'<script src="/admin/assets/security-alerts.js" defer></script>':''}${automationActivity?'<script src="/admin/assets/order-automation-activity.js" defer></script>':''}${pathname==="/admin"||pathname==="/admin/"?'<script src="/admin/assets/overview-shopify-throttle.js" defer></script><script src="/admin/assets/overview-uninstall-alert.js" defer></script>':''}</body>`);
}

export const adminShellJs=`(()=>{const workspace=()=>document.querySelector('#workspace'),token=()=>document.querySelector('#token'),connect=()=>document.querySelector('#connect'),environment=()=>document.querySelector('.environment'),welcome=()=>document.querySelector('#welcome');async function load(){const field=workspace(),secret=(token()?.value||sessionStorage.getItem('storzy.adminToken')||'').trim();if(welcome()&&sessionStorage.getItem('storzy.workspace'))welcome().hidden=true;if(!field||!secret)return;try{const response=await fetch('/api/admin/workspaces?limit=100',{headers:{Authorization:'Bearer '+secret}});if(!response.ok)return;const body=await response.json(),items=Array.isArray(body.data)?body.data:[],list=document.createElement('datalist');list.id='workspace-options';list.replaceChildren(...items.map(item=>{const option=document.createElement('option');option.value=item.id;option.label=item.name+' · '+item.status;return option}));document.querySelector('#workspace-options')?.remove();document.body.append(list);field.setAttribute('list',list.id);field.setAttribute('autocomplete','off');const current=items.find(item=>item.id===field.value)||items.find(item=>item.id===sessionStorage.getItem('storzy.workspace'));if(current){field.value=current.id;if(environment())environment().innerHTML='<i></i>'+current.name;if(welcome())welcome().hidden=true}else if(items.length===1&&!field.value){field.value=items[0].id;if(environment())environment().innerHTML='<i></i>'+items[0].name}field.addEventListener('change',()=>{const selected=items.find(item=>item.id===field.value);if(selected&&environment())environment().innerHTML='<i></i>'+selected.name},{once:true})}catch{}}function run(){load();connect()?.addEventListener('click',()=>queueMicrotask(load))}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run()})();`;

export const adminAuthSessionJs=`(()=>{const original=window.fetch.bind(window),key='storzy.adminToken';let notified=false;function serverSession(){return sessionStorage.getItem(key)==='session'}function normalized(input,init={}){if(!serverSession())return{input,init};const inherited=input instanceof Request?input.headers:undefined,headers=new Headers(init.headers||inherited);if(headers.get('Authorization')==='Bearer session')headers.delete('Authorization');return{input,init:{...init,headers,credentials:init.credentials||'same-origin'}}}async function adminFetch(input,init){const request=normalized(input,init),response=await original(request.input,request.init);if(response.status===401){try{const body=await response.clone().json();if(body?.error?.code==='ADMIN_AUTH_REQUIRED')notify()}catch{}}return response}window.fetch=adminFetch;window.storzyAdminFetch=adminFetch;function sessionMode(){sessionStorage.setItem(key,'session');document.documentElement.classList.add('server-session');const field=document.querySelector('#token');if(field){field.value='session';field.closest('.setup')?.classList.add('session-connected')}if(document.querySelector('.session-logout'))return;const nav=document.querySelector('.app-nav');if(nav){const button=document.createElement('button');button.className='session-logout';button.type='button';button.textContent='로그아웃';button.onclick=async()=>{await original('/api/auth/admin/session',{method:'DELETE',credentials:'same-origin'});sessionStorage.removeItem(key);location.replace('/admin/login')};nav.append(button)}}function notify(){if(notified)return;notified=true;sessionStorage.removeItem(key);const show=()=>{if(document.querySelector('.auth-expired'))return;const banner=document.createElement('div');banner.className='auth-expired';banner.setAttribute('role','alert');banner.innerHTML='<b>관리자 세션이 만료되었습니다.</b><span><a href="/admin/login">다시 로그인해 주세요.</a></span>';document.body.prepend(banner);const token=document.querySelector('#token');if(token)token.value=''};document.body?show():document.addEventListener('DOMContentLoaded',show,{once:true})}const run=()=>{if(serverSession())sessionMode();else original('/api/auth/admin/session',{credentials:'same-origin'}).then(r=>r.json()).then(body=>{if(body.data?.authenticated){sessionStorage.setItem(key,'session');location.reload()}else location.replace('/admin/login')}).catch(()=>location.replace('/admin/login'))};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run()})();`;

export const adminKoreanJs = `(()=>{const words=new Map(Object.entries({
'Store operations':'스토어 운영 현황','From brand profile to delivery, in one view.':'브랜드 프로필부터 배송까지 한 화면에서 관리합니다.','Refresh':'새로고침','Workspace UUID':'워크스페이스 UUID','Admin API token':'관리자 API 토큰','Connect':'연결','Pipeline':'자동화 파이프라인','Needs attention':'확인이 필요한 항목','Connect a workspace.':'워크스페이스를 연결해 주세요.','Connect a workspace to load exceptions.':'예외 주문을 불러오려면 워크스페이스를 연결해 주세요.','No active alerts.':'확인이 필요한 항목이 없습니다.',
'Catalog review':'상품 검토','Approve deterministic candidates, then review AI-generated product content.':'정량 평가된 상품 후보를 승인하고 AI가 생성한 상품 콘텐츠를 검토합니다.','Product candidates':'상품 후보','Product content':'상품 콘텐츠','Operator ID':'담당자 ID','No candidates.':'상품 후보가 없습니다.','Approve':'승인','Reject':'거절','Review JSON':'JSON 검토','Save new revision':'새 버전 저장','Approve current revision':'현재 버전 승인','Product content JSON':'상품 콘텐츠 JSON','Saving creates a new immutable editor revision. Pricing must remain equal to the approved candidate.':'저장하면 변경 불가능한 새 편집 버전이 생성됩니다. 가격은 승인된 후보와 같아야 합니다.',
'Build your Brand Profile':'브랜드 프로필 만들기','Answer twelve questions. Review and edit the structured result before approval.':'12개 질문에 답한 뒤 구조화된 결과를 검토하고 승인하세요.','Brand name':'브랜드명','Target countries':'대상 국가','Primary audience':'주요 고객','Style keywords':'스타일 키워드','Target price range':'목표 가격대','Primary colors':'주요 컬러','Initial product count':'초기 상품 수','Brand voice':'브랜드 말투','Brand story':'브랜드 스토리','Differentiator':'차별점','Preferred products':'선호 상품','Constraints':'제약 사항','Generate Brand Profile':'브랜드 프로필 생성','Edit valid JSON and save it as a new immutable revision. The approved profile remains active until the new revision is approved.':'유효한 JSON을 수정해 새 버전으로 저장할 수 있습니다. 새 버전이 승인되기 전까지 기존 승인 프로필이 유지됩니다.','Save as new revision':'새 버전으로 저장','Approve current revision':'현재 버전 승인','Revision history':'버전 이력','Open any revision to inspect it. Only review-required revisions can be approved.':'버전을 열어 내용을 확인할 수 있습니다. 검토 대기 중인 버전만 승인할 수 있습니다.','No revisions yet.':'아직 생성된 버전이 없습니다.','Waiting for generation…':'생성 작업을 기다리는 중입니다…',
'Store configuration':'스토어 구성','Generate, edit, approve, and monitor Shopify publication without changing Liquid code.':'Liquid 코드를 수정하지 않고 Shopify 스토어 구성을 생성·편집·승인·게시합니다.','Generate from approved brand':'승인된 브랜드로 생성','Select a revision':'버전을 선택해 주세요','Approve':'승인','Retry failed publication':'실패한 게시 다시 시도',
'Designs & Printful mockups':'디자인 및 Printful 목업','Register verified design files and review missing print-area guidance before automation resumes.':'검증된 디자인 파일을 등록하고 인쇄 영역 정보가 없는 항목을 검토합니다.','A design is required before mockup generation.':'목업을 생성하려면 디자인이 필요합니다.','Register design':'디자인 등록','Update design':'디자인 수정','Review print area':'인쇄 영역 검토','HTTPS design file URL':'HTTPS 디자인 파일 URL','Print placement':'인쇄 위치','Print technique':'인쇄 기법','Mockup style IDs':'목업 스타일 ID','Register and queue mockup':'등록 후 목업 생성','Review print area':'인쇄 영역 검토','Enter the verified physical print area. The saved image pixels will be checked again before queuing.':'확인된 실제 인쇄 영역을 입력하세요. 작업 등록 전에 이미지 픽셀을 다시 검증합니다.','Print width (inches)':'인쇄 너비(인치)','Print height (inches)':'인쇄 높이(인치)','Target DPI':'목표 DPI','Review reason':'검토 사유','Validate and resume mockup':'검증 후 목업 재개','Close':'닫기','No approved candidates.':'승인된 상품 후보가 없습니다.',
'Order operations':'주문 운영','Review exceptions before they reach production.':'제작에 전달되기 전에 예외 주문을 검토합니다.','Held + waiting':'보류 + 대기','Order exception':'주문 예외','Line items':'주문 상품','Decision':'처리 결정','Required for approval or rejection':'승인 또는 거절 사유를 입력하세요','Revalidate':'다시 검증','Manual approve':'수동 승인','Reject order':'주문 거절','Audit history':'감사 이력','No orders.':'주문이 없습니다.','Status filter':'상태 필터',
'OPERATIONS CONSOLE':'운영 관리 콘솔','MVP workspace':'MVP 워크스페이스','Overview':'운영 현황','Brand':'브랜드','Store':'스토어','Catalog':'상품','Designs':'디자인','Orders':'주문','Close':'닫기'
}));const status=new Map(Object.entries({'APPROVED':'승인됨','REJECTED':'거절됨','UNREVIEWED':'미검토','REVIEW_REQUIRED':'검토 필요','GENERATION_FAILED':'생성 실패','GENERATING':'생성 중','PENDING':'대기','RUNNING':'처리 중','SUCCEEDED':'완료','FAILED':'실패','WAITING':'대기','HELD':'보류','WAITING_REMOTE':'외부 처리 대기','GUIDELINE_MISSING':'규격 확인 필요','PASSED':'검증 통과','NO DESIGN':'디자인 없음'}));function translateText(node){if(node.parentElement?.closest('script,style,textarea,pre,code'))return;const raw=node.nodeValue||'',trim=raw.trim(),translated=words.get(trim)||status.get(trim);if(translated)node.nodeValue=raw.replace(trim,translated);else{const numbered=trim.match(/^([0-9]+)[.] (.+)$/);if(numbered&&words.has(numbered[2]))node.nodeValue=raw.replace(trim,numbered[1]+'. '+words.get(numbered[2]));const revision=trim.match(/^Revision ([0-9]+)$/);if(revision)node.nodeValue=raw.replace(trim,'버전 '+revision[1]);const orders=trim.match(/^([0-9]+) orders$/);if(orders)node.nodeValue=raw.replace(trim,orders[1]+'건의 주문')}}function walk(root){if(root.nodeType===Node.TEXT_NODE){translateText(root);return}if(root.nodeType!==Node.ELEMENT_NODE&&root.nodeType!==Node.DOCUMENT_NODE)return;const el=root;if(el instanceof HTMLElement){for(const attr of ['placeholder','aria-label','title']){const value=el.getAttribute(attr);if(value&&(words.has(value)||status.has(value)))el.setAttribute(attr,words.get(value)||status.get(value))}}for(const child of root.childNodes)walk(child)}function run(){document.documentElement.lang='ko';const titles={'STORZY · Operations':'STORZY · 운영 현황','STORZY · Brand Onboarding':'STORZY · 브랜드 온보딩','STORZY · Store configuration':'STORZY · 스토어 구성','STORZY · Catalog Review':'STORZY · 상품 검토','STORZY · Designs & mockups':'STORZY · 디자인 및 목업','STORZY · Order Operations':'STORZY · 주문 운영'};document.title=titles[document.title]||document.title;walk(document.body);new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(walk))).observe(document.body,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run()})();`;

export const adminSystemCss = `
:root{--ink:#121713;--ink-2:#253029;--paper:#f2f4ec;--surface:rgba(255,255,252,.88);--line:rgba(18,23,19,.11);--muted:#667069;--acid:#c9f135;--acid-soft:#edffc2;--blue:#b8d7ff;--red:#ffb9ad;--shadow:0 20px 55px rgba(29,42,32,.08);font-family:Inter,"Segoe UI",ui-sans-serif,system-ui,sans-serif;color:var(--ink);background:var(--paper);font-synthesis:none}
*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 8% 0%,rgba(201,241,53,.18),transparent 28rem),radial-gradient(circle at 95% 12%,rgba(184,215,255,.25),transparent 30rem),var(--paper);color:var(--ink)}
body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.22;background-image:linear-gradient(rgba(18,23,19,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(18,23,19,.035) 1px,transparent 1px);background-size:32px 32px;mask-image:linear-gradient(to bottom,#000,transparent 75%)}
.app-nav{position:sticky;top:14px;z-index:50;max-width:1280px;margin:14px auto 0;padding:9px 10px 9px 12px;display:flex;align-items:center;gap:24px;border:1px solid rgba(255,255,255,.8);border-radius:18px;background:rgba(18,23,19,.94);box-shadow:0 14px 36px rgba(18,23,19,.18);backdrop-filter:blur(18px)}
.auth-expired{position:sticky;top:0;z-index:100;display:flex;justify-content:center;gap:10px;padding:11px 16px;background:#85281f;color:#fff;font-size:13px}.auth-expired span,.auth-expired a{color:#ffe7e3}.server-session #token,.server-session .onboarding-auth{display:none!important}.session-connected:before{content:"서버 세션으로 안전하게 연결됨";align-self:center;padding:0 8px;color:#4f6449;font-size:12px;font-weight:800}.session-logout{min-height:32px!important;padding:0 10px!important;border-color:#ffffff2b!important;background:#ffffff0f!important;color:#dce3dd!important;font-size:11px!important}.session-logout:hover{background:#ffffff20!important}
.app-brand{display:flex;align-items:center;gap:10px;color:#fff;text-decoration:none;font-size:13px;font-weight:900;letter-spacing:.14em}.brand-mark{display:grid;place-items:center;width:30px;height:30px;border-radius:10px;background:var(--acid);color:var(--ink);font-size:15px;letter-spacing:0}.app-links{display:flex;align-items:center;gap:3px;flex:1}.app-links a{padding:9px 12px;border-radius:10px;color:#aeb8b0;text-decoration:none;font-size:13px;font-weight:700;transition:.18s ease}.app-links a:hover{color:#fff;background:#ffffff12}.app-links a.active{background:#fff;color:var(--ink)}.environment{display:flex;align-items:center;gap:7px;padding:0 9px;color:#b7c0b9;font-size:11px;font-weight:700}.environment i{width:7px;height:7px;border-radius:99px;background:var(--acid);box-shadow:0 0 0 4px #c9f13522}
.shell{position:relative;width:min(100% - 32px,1240px)!important;max-width:1240px!important;margin:0 auto!important;padding:64px 0 80px!important}.shell>.nav{display:none!important}
h1{max-width:800px;margin:0 0 10px!important;font-size:clamp(34px,5vw,58px)!important;line-height:.96!important;letter-spacing:-.055em!important;font-weight:850!important}h2{font-size:22px;letter-spacing:-.025em}h3{letter-spacing:-.015em}.muted,.sub{color:var(--muted)!important;line-height:1.55}.hero,.top{margin-bottom:30px!important}.hero>div:before,.top>div:before{content:"운영 관리 콘솔";display:block;margin-bottom:13px;color:#667069;font-size:10px;font-weight:900;letter-spacing:.16em}
.panel,.card,.metric,.setup,.toolbar,.drawer{border:1px solid rgba(255,255,255,.92)!important;background:var(--surface)!important;box-shadow:var(--shadow)!important;backdrop-filter:blur(12px)}.panel,.setup,.toolbar,.card,.metric{border-radius:22px!important}.panel{padding:24px!important}.setup{padding:12px!important;margin:24px 0!important}.card{padding:20px!important;transition:transform .18s ease,box-shadow .18s ease}.card:hover{transform:translateY(-2px);box-shadow:0 24px 60px rgba(29,42,32,.12)!important}
input,select,textarea,button{font:inherit}input,select,textarea{border:1px solid var(--line)!important;border-radius:12px!important;background:#fff!important;color:var(--ink)!important;outline:none;transition:border-color .18s,box-shadow .18s}input:focus,select:focus,textarea:focus{border-color:#87a819!important;box-shadow:0 0 0 4px rgba(201,241,53,.25)!important}button{min-height:42px;border:1px solid var(--line)!important;border-radius:12px!important;background:#fff!important;color:var(--ink)!important;font-weight:760!important;transition:transform .16s ease,background .16s ease,box-shadow .16s ease}button:hover:not(:disabled){transform:translateY(-1px);box-shadow:0 7px 16px rgba(18,23,19,.10)}button.primary,#connect,#refresh{background:var(--ink)!important;border-color:var(--ink)!important;color:#fff!important}button.primary:hover,#connect:hover,#refresh:hover{background:var(--ink-2)!important}.danger,button.danger{background:#9d3028!important;color:#fff!important}
.metrics{gap:14px!important}.metric{position:relative;overflow:hidden;min-height:132px;padding:22px!important}.metric:after{content:"";position:absolute;right:-18px;bottom:-28px;width:92px;height:92px;border-radius:50%;background:var(--acid-soft)}.metric:nth-child(2):after{background:#dfeaff}.metric:nth-child(3):after{background:#ffe9bb}.metric:nth-child(4):after{background:#ffd8d1}.metric .value{position:relative;z-index:1;font-size:38px!important;line-height:1;font-variant-numeric:tabular-nums}.metric .meta{position:relative;z-index:1;text-transform:uppercase;letter-spacing:.08em;font-weight:750}
.welcome{display:flex;align-items:center;justify-content:space-between;gap:24px;margin:0 0 20px;padding:24px 26px;border-radius:22px;background:var(--ink);color:#fff;box-shadow:0 20px 55px rgba(18,23,19,.16)}.welcome[hidden]{display:none}.welcome h2{margin:5px 0 7px;font-size:24px}.welcome p{margin:0;color:#b9c3bb}.welcome .eyebrow{color:var(--acid);font-size:10px;font-weight:900;letter-spacing:.16em}.welcome a{flex:none;padding:12px 16px;border-radius:12px;background:var(--acid);color:var(--ink);font-weight:850;text-decoration:none}
.pipeline{gap:10px!important}.stage{position:relative;overflow:hidden;min-height:124px!important;padding:16px!important;border:1px solid var(--line);border-radius:15px!important;background:#fff!important}.stage:before{content:"";display:block;width:28px;height:4px;margin-bottom:14px;border-radius:9px;background:var(--acid)}.stage:nth-child(3n+2):before{background:#75aaf0}.stage:nth-child(3n):before{background:#f3b04c}.stage strong{font-variant-numeric:tabular-nums}
.badge{display:inline-flex!important;align-items:center!important;border-radius:999px!important;padding:5px 9px!important;font-size:10px!important;font-weight:850!important;letter-spacing:.04em!important}.alert{align-items:center;border-color:var(--line)!important}.empty{border:1px dashed rgba(18,23,19,.16);border-radius:15px;background:rgba(255,255,255,.45)}
.tabs{padding:5px;width:max-content;border:1px solid var(--line);border-radius:15px;background:#fff}.tabs button{border:0!important}.tabs button.active{background:var(--ink)!important;color:#fff!important}.json-editor,.editor,#json{border-radius:15px!important;background:#111713!important;color:#eaf1e9!important;border-color:#28332b!important;box-shadow:inset 0 1px 0 #ffffff12!important}.drawer{border-radius:24px 0 0 24px!important;background:#f9faf5!important}.error{border:1px solid #f2a99e!important;border-radius:13px!important;background:#fff0ed!important}
::selection{background:var(--acid);color:var(--ink)}
@media(max-width:900px){.app-nav{top:8px;margin:8px;overflow-x:auto}.environment{display:none}.app-links{min-width:max-content}.shell{width:min(100% - 24px,1240px)!important;padding-top:42px!important}.pipeline{grid-template-columns:repeat(2,1fr)!important}}
@media(max-width:620px){.app-nav{position:relative;top:0;display:grid;grid-template-columns:auto 1fr;align-items:start;gap:10px;margin:8px;border-radius:15px;overflow:visible}.app-brand{padding:6px 0}.app-brand span:last-child{display:none}.app-links{display:grid;grid-template-columns:repeat(3,1fr);width:100%;min-width:0;gap:3px}.app-links a{padding:7px 5px;text-align:center;font-size:11px}.shell{width:min(100% - 20px,1240px)!important;padding-top:30px!important}h1{font-size:38px!important}.metrics,.grid,.pipeline{grid-template-columns:1fr!important}.setup{grid-template-columns:1fr!important}.panel{padding:18px!important}.welcome{align-items:flex-start;flex-direction:column}.welcome a{width:100%;text-align:center}}
`;
