export const orderReconciliationScansJs=`(()=>{
const section=document.querySelector('.reconciliation'),tabs=section?.querySelector('.reconciliation-tabs'),container=section?.querySelector('.reconciliation-issues');
if(!section||!tabs||!container)return;
const button=document.createElement('button');button.type='button';button.dataset.reconciliationTab='scans';button.textContent='스캔 이력';tabs.querySelector('[data-reconciliation-tab="runs"]')?.before(button);
const actions=section.querySelector('.reconciliation-actions'),operatorInput=document.createElement('input');operatorInput.id='reconciliation-actor';operatorInput.placeholder='담당자 ID';operatorInput.setAttribute('aria-label','주문 대조 담당자 ID');operatorInput.maxLength=100;operatorInput.value=sessionStorage.getItem('storzy.operatorId')||document.querySelector('#actor')?.value?.trim()||'admin-ui';actions?.prepend(operatorInput);operatorInput.addEventListener('change',()=>{const value=operatorInput.value.trim()||'admin-ui';operatorInput.value=value;sessionStorage.setItem('storzy.operatorId',value);const drawerActor=document.querySelector('#actor');if(drawerActor)drawerActor.value=value});
const issueFilter=document.createElement('select');issueFilter.id='reconciliation-issue-filter';issueFilter.setAttribute('aria-label','스캔 불일치 유형');issueFilter.innerHTML='<option value="">불일치 전체</option><option value="MISSING_LOCAL_ORDER">누락 주문</option><option value="CANCELLATION_MISMATCH">취소 상태</option><option value="FINANCIAL_STATUS_MISMATCH">결제 상태</option>';actions?.prepend(issueFilter);
const orderSearch=document.createElement('input');orderSearch.id='reconciliation-order-search';orderSearch.placeholder='Shopify 주문 ID 검색';orderSearch.setAttribute('aria-label','Shopify 주문 ID 검색');orderSearch.maxLength=100;actions?.prepend(orderSearch);
const auth=()=>sessionStorage.getItem('storzy.adminToken')||document.querySelector('#token')?.value||'',workspace=()=>sessionStorage.getItem('storzy.workspace')||document.querySelector('#workspace')?.value||'',actor=()=>operatorInput.value.trim()||sessionStorage.getItem('storzy.operatorId')||'admin-ui',esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const names={MISSING_LOCAL_ORDER:'누락 주문',CANCELLATION_MISMATCH:'취소 상태 불일치',FINANCIAL_STATUS_MISMATCH:'결제 상태 불일치'},breakdown=scan=>{const values=scan.breakdown||{},items=Object.entries(names).map(([key,label])=>[label,values[key]]).filter(item=>Number(item[1])>0);return items.length?items.map(item=>item[0]+' '+item[1]+'건').join(' · '):'불일치 없음'};
async function request(path){const response=await fetch(path,{headers:{Authorization:'Bearer '+auth()}}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error?.message||'요청을 처리하지 못했습니다.');return body.data||[]}
async function details(scanId,target){const offset=Number(target.dataset.offset||0),filter=issueFilter.value?'&issueType='+encodeURIComponent(issueFilter.value):'',search=orderSearch.value.trim()?'&orderQuery='+encodeURIComponent(orderSearch.value.trim()):'';target.disabled=true;try{const rows=await request('/api/workspaces/'+encodeURIComponent(workspace())+'/order-reconciliation/scans/'+encodeURIComponent(scanId)+'/issues?limit=100&offset='+offset+filter+search),box=target.closest('.reconciliation-issue').querySelector('.scan-details'),html=rows.map(item=>'<div class="audit-item"><b>'+esc(names[item.issue_type]||item.issue_type)+'</b> · '+esc(item.shopify_order_id)+'<br>로컬 '+esc(item.local_value||'없음')+' / Shopify '+esc(item.remote_value||'없음')+'</div>').join('');box.hidden=false;if(offset===0)box.innerHTML=html||'<div class="audit-item">저장된 불일치 상세가 없습니다.</div>';else box.insertAdjacentHTML('beforeend',html);if(rows.length===100){target.dataset.offset=String(offset+100);target.textContent='다음 100건'}else{target.dataset.offset='0';target.textContent='상세 새로고침'}}catch(error){alert(error.message)}finally{target.disabled=false}}
async function exportHistory(scanId,target){target.disabled=true;try{const rows=await request('/api/workspaces/'+encodeURIComponent(workspace())+'/order-reconciliation/scans/'+encodeURIComponent(scanId)+'/exports?limit=50'),box=target.closest('.reconciliation-issue').querySelector('.scan-details');box.hidden=false;box.innerHTML=rows.length?rows.map(item=>'<div class="audit-item"><b>'+esc(item.actor_id)+'</b> · '+new Date(item.created_at).toLocaleString('ko-KR')+' · '+esc(item.issue_count)+'건<br>'+esc(item.reason)+'</div>').join(''):'<div class="audit-item">CSV 내보내기 이력이 없습니다.</div>';target.textContent='내보내기 이력 새로고침'}catch(error){alert(error.message)}finally{target.disabled=false}}
async function download(scanId,target){const operator=actor(),reason=prompt('CSV 내보내기 사유를 입력해 주세요.');if(reason===null)return;if(!reason.trim())return alert('내보내기 사유가 필요합니다.');sessionStorage.setItem('storzy.operatorId',operator);target.disabled=true;try{const response=await fetch('/api/workspaces/'+encodeURIComponent(workspace())+'/order-reconciliation/scans/'+encodeURIComponent(scanId)+'/export.csv',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+auth()},body:JSON.stringify({actorId:operator,reason:reason.trim()})});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error?.message||'CSV를 내려받지 못했습니다.')}const url=URL.createObjectURL(await response.blob()),link=document.createElement('a');link.href=url;link.download='storzy-reconciliation-'+scanId+'.csv';document.body.append(link);link.click();link.remove();URL.revokeObjectURL(url);target.textContent='CSV 다시 내보내기'}catch(error){alert(error.message)}finally{target.disabled=false}}
function bind(){container.querySelectorAll('[data-scan-details]').forEach(control=>control.onclick=()=>details(control.dataset.scanDetails,control));container.querySelectorAll('[data-scan-export]').forEach(control=>{control.onclick=()=>download(control.dataset.scanExport,control);const history=document.createElement('button');history.type='button';history.dataset.exportHistory=control.dataset.scanExport;history.textContent='내보내기 이력';control.after(history)});container.querySelectorAll('[data-export-history]').forEach(control=>control.onclick=()=>exportHistory(control.dataset.exportHistory,control))}
async function load(){if(!workspace()||!auth()){container.innerHTML='<div class="reconciliation-history reconciliation-issue">워크스페이스를 먼저 연결해 주세요.</div>';return}container.innerHTML='<div class="reconciliation-history reconciliation-issue">스캔 이력을 불러오는 중입니다.</div>';try{const search=orderSearch.value.trim()?'&orderQuery='+encodeURIComponent(orderSearch.value.trim()):'',rows=await request('/api/workspaces/'+encodeURIComponent(workspace())+'/order-reconciliation/scans?limit=50'+search);container.innerHTML=rows.length?rows.map(scan=>'<div class="reconciliation-issue reconciliation-history"><div><b>대조 스캔</b> · '+new Date(scan.created_at).toLocaleString('ko-KR')+'<br><span>Shopify '+esc(scan.remote_order_count)+'건 · 로컬 일치 '+esc(scan.matched_order_count)+'건 · 불일치 '+esc(scan.issue_count)+'건 · 조회 시작 '+new Date(scan.window_started_at).toLocaleString('ko-KR')+'</span><div class="audit-list"><div class="audit-item">유형별 · '+esc(breakdown(scan))+'</div><div class="audit-item">실행자 '+esc(scan.actor_id)+'</div>'+(Number(scan.export_count)>0?'<div class="audit-item">CSV 내보내기 '+esc(scan.export_count)+'회 · 최근 '+esc(scan.latest_export?.actorId||'알 수 없음')+' · '+new Date(scan.latest_export?.createdAt).toLocaleString('ko-KR')+'<br>사유 · '+esc(scan.latest_export?.reason||'기록 없음')+'</div>':'')+'<div class="scan-details" hidden></div></div></div>'+(Number(scan.issue_count)>0?'<div class="issue-buttons"><button data-scan-details="'+esc(scan.id)+'">불일치 상세</button><button data-scan-export="'+esc(scan.id)+'">CSV 내보내기</button></div>':'')+'</div>').join(''):'<div class="reconciliation-history reconciliation-issue">검색 조건에 맞는 대조 스캔이 없습니다.</div>';bind()}catch(error){container.innerHTML='<div class="reconciliation-issue">'+esc(error.message)+'</div>'}}
button.onclick=async()=>{tabs.querySelectorAll('[data-reconciliation-tab]').forEach(item=>item.classList.toggle('active',item===button));await load()};
const resetDetails=()=>{container.querySelectorAll('[data-scan-details]').forEach(control=>{control.dataset.offset='0';control.textContent='불일치 상세'});container.querySelectorAll('.scan-details').forEach(box=>{box.hidden=true;box.innerHTML=''})};issueFilter.onchange=resetDetails;orderSearch.oninput=resetDetails;orderSearch.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();load()}};
})();`;
