export const printfulDraftCleanupCss=`
.draft-cleanup{border:1px solid #edc6be;background:#fff7f5;border-radius:12px;padding:15px}
.draft-cleanup h3{margin:0 0 7px;color:#84291f}.draft-cleanup p{margin:0 0 12px}
.draft-cleanup-meta{display:grid;grid-template-columns:130px 1fr;gap:7px;margin-bottom:12px;font-size:13px}
.draft-cleanup-actions{display:flex;gap:8px;align-items:center}.draft-cleanup-actions button{background:#9c2f24;color:#fff;border-color:#9c2f24}
.draft-cleanup-message{font-size:12px;margin-top:9px;color:#84291f}
.draft-cleanup-history{margin-top:14px;padding-top:12px;border-top:1px solid #edc6be}.draft-cleanup-history h4{margin:0 0 8px}
.draft-cleanup-history-item{display:grid;grid-template-columns:1fr auto;gap:4px 12px;padding:9px 0;border-top:1px solid #f2ddd8;font-size:12px}
.draft-cleanup-history-item:first-of-type{border-top:0}.draft-cleanup-history-item time{color:#706d65}.draft-cleanup-history-item p{grid-column:1/-1;margin:0;color:#706d65}
.draft-cleanup[hidden]{display:none}@media(max-width:600px){.draft-cleanup-actions{display:grid}.draft-cleanup-history-item{grid-template-columns:1fr}}
`;

export const printfulDraftCleanupJs=`(()=>{
const drawer=document.querySelector('#drawer');if(!drawer)return;let panel;
const workspace=()=>((document.querySelector('#workspace')?.value||sessionStorage.getItem('storzy.workspace')||'').trim());
const token=()=>((document.querySelector('#token')?.value||sessionStorage.getItem('storzy.adminToken')||'').trim());
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function mount(){if(panel)return;panel=document.createElement('section');panel.className='section draft-cleanup';panel.hidden=true;panel.innerHTML='<h3>Printful 원격 초안 정리</h3><p class="muted">자동화 중지 후 남은 미확정 초안만 삭제합니다. 제작이 시작된 주문은 삭제할 수 없습니다.</p><div class="draft-cleanup-meta"></div><div class="draft-cleanup-actions"><button type="button">원격 초안 삭제</button><span class="muted">위 담당자와 처리 사유를 사용합니다.</span></div><div class="draft-cleanup-message" role="status"></div><div class="draft-cleanup-history"></div>';drawer.append(panel);panel.querySelector('button').onclick=cleanup}
function history(items){const host=panel.querySelector('.draft-cleanup-history');host.hidden=!items.length;host.innerHTML=items.length?'<h4>최근 정리 이력</h4>'+items.map(item=>'<div class="draft-cleanup-history-item"><b>'+esc(item.actor_id)+'</b><time datetime="'+esc(item.created_at)+'">'+new Date(item.created_at).toLocaleString('ko-KR')+'</time><p>Printful '+esc(item.remote_order_id)+' · '+esc(item.reason)+'</p></div>').join(''):''}
async function inspect(){mount();const id=drawer.dataset.id,workspaceId=workspace();if(drawer.hidden||!id||!workspaceId){panel.hidden=true;return}const headers={...(token()?{Authorization:'Bearer '+token()}:{})},detailUrl='/api/workspaces/'+encodeURIComponent(workspaceId)+'/order-exceptions/'+encodeURIComponent(id),historyUrl='/api/workspaces/'+encodeURIComponent(workspaceId)+'/orders/'+encodeURIComponent(id)+'/printful-draft/cleanup-actions?limit=20',[detailResponse,historyResponse]=await Promise.all([fetch(detailUrl,{headers}),fetch(historyUrl,{headers})]),detailBody=await detailResponse.json().catch(()=>({})),historyBody=await historyResponse.json().catch(()=>({}));if(!detailResponse.ok)return;const job=detailBody.data.printfulJob,items=historyResponse.ok&&Array.isArray(historyBody.data)?historyBody.data:[],eligible=job?.status==='HELD'&&job.remote_order_id&&!job.confirmed_response;panel.hidden=!eligible&&!items.length;panel.querySelector('.draft-cleanup-actions').hidden=!eligible;panel.querySelector('.draft-cleanup-meta').innerHTML=eligible?'<span>Printful 주문 ID</span><b>'+esc(job.remote_order_id)+'</b><span>로컬 상태</span><b>보류됨</b>':'';if(eligible)panel.dataset.remoteId=job.remote_order_id;history(items)}
async function cleanup(){const id=drawer.dataset.id,actorId=document.querySelector('#actor')?.value.trim(),reason=document.querySelector('#reason')?.value.trim(),remoteId=panel.dataset.remoteId;if(!actorId||!reason){panel.querySelector('.draft-cleanup-message').textContent='담당자와 처리 사유를 먼저 입력해 주세요.';return}if(!confirm('Printful 원격 초안 '+remoteId+'을 삭제할까요? 이 작업은 되돌릴 수 없습니다.'))return;const button=panel.querySelector('button');button.disabled=true;try{const response=await fetch('/api/workspaces/'+encodeURIComponent(workspace())+'/orders/'+encodeURIComponent(id)+'/printful-draft/cleanup',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token(),'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({actorId,reason})}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error?.message||'원격 초안 정리에 실패했습니다.');await inspect();panel.querySelector('.draft-cleanup-message').textContent=body.data.alreadyAbsent?'이미 삭제된 초안을 로컬 상태에 반영했습니다.':'원격 초안을 안전하게 삭제했습니다.';window.dispatchEvent(new Event('storzy:automation-changed'))}catch(error){panel.querySelector('.draft-cleanup-message').textContent=error.message}finally{button.disabled=false}}
new MutationObserver(()=>queueMicrotask(inspect)).observe(drawer,{attributes:true,attributeFilter:['hidden','data-id']});mount();
})();`;
