import { createServer } from "node:http";
import { BrandProfileService } from "./brand/service.js";
import { PostgresBrandProfileStore } from "./brand/postgres-store.js";
import { loadConfig } from "./config.js";
import { createPool } from "./db/pool.js";
import { createApp } from "./http/app.js";
import { JsonLogger } from "./observability/logger.js";
import { PostgresNotificationService } from "./notifications/postgres-notification-service.js";
import { PostgresCandidateReviewService } from "./candidates/postgres-review-service.js";
import { ProductContentReviewService } from "./content/review-service.js";
import { DesignAssetService } from "./mockups/design-service.js";
import { PrintfulMockupWebhookService } from "./mockups/webhook-service.js";
import { PrintfulWebhookRouter } from "./mockups/printful-webhook-router.js";
import { ShopifyOrderWebhookService } from "./orders/shopify-webhook-service.js";
import { ShopifyOrderWebhookRouter } from "./orders/shopify-webhook-router.js";
import { WebhookHealthService } from "./integrations/webhook-health-service.js";
import {ShopifyPrivacyWebhookService} from "./privacy/shopify-privacy-webhook.js";
import {PrivacyRequestService} from "./privacy/request-service.js";
import {PrivacySlaAlertService} from "./privacy/sla-alert-service.js";
import { PrintfulFulfillmentHandler } from "./fulfillment/printful-handler.js";
import { OrderExceptionService } from "./orders/exception-service.js";
import {ReturnCaseService} from "./orders/return-case-service.js";
import {OrderReconciliationService} from "./orders/shopify-reconciliation.js";
import { AdminOverviewService } from "./admin/overview-service.js";
import { StoreConfigService } from "./storefront/config-service.js";
import { HttpDesignFileInspector, PreviewDesignFileInspector } from "./mockups/file-inspector.js";
import { PreviewOrderService } from "./orders/preview-order-service.js";
import { PreviewFulfillmentService } from "./fulfillment/preview-service.js";
import { PreviewDesignUploadService } from "./mockups/preview-upload-service.js";
import { CredentialCipher } from "./integrations/credential-cipher.js";
import { IntegrationConnectionRepository } from "./integrations/connection-repository.js";
import { ShopifyOAuthService } from "./integrations/shopify-oauth.js";
import {ShopifyAccessTokenProvider} from "./integrations/shopify-access-token-provider.js";
import {DatabaseReadinessService} from "./operations/database-readiness.js";
import{ShopifyTokenAlertDeliveryService}from"./integrations/shopify-token-alert-delivery.js";
import{ProcessHeartbeatStore}from"./operations/process-heartbeat.js";
import{OrderAutomationControlService}from"./orders/automation-control.js";
import{WorkspacePrintfulOrderClients}from"./orders/workspace-printful-client.js";
import{RemoteDraftCleanupService}from"./orders/remote-draft-cleanup.js";
import{loadMigrations}from"./db/migration-runner.js";
import{resolve}from"node:path";
import{fileURLToPath}from"node:url";
import{access}from"node:fs/promises";
import{ShopifyAppUninstalledWebhookService}from"./integrations/shopify-app-uninstalled.js";
import{AdminSessionService}from"./auth/admin-session-service.js";

const config = loadConfig();
const pool = createPool(config.databaseUrl);
const service = new BrandProfileService(new PostgresBrandProfileStore(pool));
const logger = new JsonLogger(config.logLevel, { service: "storzy-api" });
const notifications = new PostgresNotificationService(pool);
const candidates = new PostgresCandidateReviewService(pool);
const contentReviews = new ProductContentReviewService(pool);
const previewDesignUploads=process.env.PREVIEW_MODE==="1"?new PreviewDesignUploadService(process.env.PREVIEW_UPLOAD_DIRECTORY?.trim()||".preview/uploads",{maxFilesPerWorkspace:Number(process.env.PREVIEW_UPLOAD_MAX_FILES??"100"),maxBytesPerWorkspace:Number(process.env.PREVIEW_UPLOAD_MAX_BYTES??String(500*1024*1024))}):undefined;
const designs = new DesignAssetService(pool,process.env.PREVIEW_MODE==="1"?new PreviewDesignFileInspector(previewDesignUploads):new HttpDesignFileInspector());
const webhookSecret=process.env.PRINTFUL_WEBHOOK_SECRET_HEX?.trim();
const fulfillmentHandler=new PrintfulFulfillmentHandler(pool);
const shopifySecret=process.env.SHOPIFY_WEBHOOK_SECRET?.trim()||process.env.SHOPIFY_API_SECRET?.trim(),orderWorkspace=process.env.SHOPIFY_ORDER_WORKSPACE_ID?.trim();
const allowedCountries=new Set((process.env.ORDER_ALLOWED_COUNTRIES??"US,JP").split(',').map(x=>x.trim().toUpperCase()).filter(Boolean));
const orderPolicy={maxOrderAmountMinor:BigInt(process.env.ORDER_MAX_AMOUNT_MINOR??"50000"),maxItemCount:Number(process.env.ORDER_MAX_ITEM_COUNT??"10"),maxCostIncreaseBasisPoints:Number(process.env.ORDER_MAX_COST_INCREASE_BPS??"1000")};
const orderExceptions=new OrderExceptionService(pool,allowedCountries,orderPolicy);
const returnCases=new ReturnCaseService(pool);
const orderReconciliation=new OrderReconciliationService(pool);
const adminOverview=new AdminOverviewService(pool);
const storeConfig=new StoreConfigService(pool);
const previewOrders=process.env.PREVIEW_MODE==="1"?new PreviewOrderService(pool):undefined;
const previewFulfillment=process.env.PREVIEW_MODE==="1"?new PreviewFulfillmentService(pool):undefined;
const credentialKey=process.env.INTEGRATION_CREDENTIAL_KEY_BASE64?.trim(),shopifyApiKey=process.env.SHOPIFY_API_KEY?.trim(),shopifyApiSecret=process.env.SHOPIFY_API_SECRET?.trim(),shopifyCallback=process.env.SHOPIFY_OAUTH_CALLBACK_URL?.trim(),shopifyScopes=(process.env.SHOPIFY_SCOPES??"").split(',').map(x=>x.trim()).filter(Boolean);
const connectionRepository=credentialKey?new IntegrationConnectionRepository(pool,CredentialCipher.fromBase64(credentialKey,process.env.INTEGRATION_CREDENTIAL_KEY_VERSION?.trim()||"v1")):undefined;
const printfulPublicKey=process.env.PRINTFUL_WEBHOOK_PUBLIC_KEY?.trim()||undefined;
const printfulWebhook=webhookSecret?(connectionRepository?new PrintfulWebhookRouter(pool,webhookSecret,printfulPublicKey,connectionRepository):new PrintfulMockupWebhookService(pool,webhookSecret,printfulPublicKey,fulfillmentHandler)):undefined;
const orderAutomation=new OrderAutomationControlService(pool,Number(process.env.PRINTFUL_ORDER_RATE_LIMIT_PER_MINUTE??"2"));
const shopifyOrders=shopifySecret?(connectionRepository?new ShopifyOrderWebhookRouter(pool,shopifySecret,connectionRepository,allowedCountries,orderPolicy,orderAutomation):orderWorkspace?new ShopifyOrderWebhookService(pool,shopifySecret,orderWorkspace,allowedCountries,orderPolicy,orderAutomation):undefined):undefined;
const shopifyOAuth=connectionRepository&&shopifyApiKey&&shopifyApiSecret&&shopifyCallback&&shopifyScopes.length?new ShopifyOAuthService(pool,connectionRepository,{apiKey:shopifyApiKey,apiSecret:shopifyApiSecret,callbackUrl:shopifyCallback,scopes:shopifyScopes}):undefined;
const shopifyAccess=connectionRepository&&shopifyApiKey&&shopifyApiSecret?new ShopifyAccessTokenProvider(connectionRepository,{apiKey:shopifyApiKey,apiSecret:shopifyApiSecret}):undefined;
const webhookHealth=new WebhookHealthService(pool);
const privacyWebhooks=shopifySecret?new ShopifyPrivacyWebhookService(pool,shopifySecret,connectionRepository):undefined;
const shopifyAppUninstalled=shopifySecret&&connectionRepository?new ShopifyAppUninstalledWebhookService(shopifySecret,connectionRepository):undefined;
const privacyRequests=new PrivacyRequestService(pool);
const privacyAlerts=new PrivacySlaAlertService(pool);
const bundledMigrations=resolve(fileURLToPath(new URL("../migrations",import.meta.url))),migrationDirectory=await access(bundledMigrations).then(()=>bundledMigrations).catch(()=>resolve("migrations"));
const readiness=new DatabaseReadinessService(pool,await loadMigrations(migrationDirectory));
const shopifyTokenAlerts=new ShopifyTokenAlertDeliveryService(pool);
const processHeartbeats=new ProcessHeartbeatStore(pool);
const printfulOrderClients=new WorkspacePrintfulOrderClients(connectionRepository,config.printfulApiBaseUrl,process.env.PRINTFUL_TOKEN?.trim()?{token:process.env.PRINTFUL_TOKEN.trim(),...(process.env.PRINTFUL_STORE_ID?.trim()?{storeId:process.env.PRINTFUL_STORE_ID.trim()}:{})}:undefined);
const remoteDraftCleanup=new RemoteDraftCleanupService(pool,printfulOrderClients);
const adminSessions=new AdminSessionService(pool,{ttlSeconds:Number(process.env.ADMIN_SESSION_TTL_SECONDS??"28800"),secure:config.nodeEnv==="production"});
const server = createServer(createApp(service, logger, notifications, candidates, contentReviews, designs, printfulWebhook, shopifyOrders, orderExceptions, config.adminApiToken||undefined,adminOverview,storeConfig,previewOrders,previewFulfillment,previewDesignUploads,process.env.PREVIEW_MODE==="1"?storeConfig:undefined,shopifyOAuth,connectionRepository,webhookHealth,privacyWebhooks,privacyRequests,privacyAlerts,returnCases,orderReconciliation,readiness,shopifyAccess,shopifyTokenAlerts,processHeartbeats,orderAutomation,remoteDraftCleanup,shopifyAppUninstalled,adminSessions));
server.listen(config.port, () => {
  logger.info("server.started", { port: config.port });
});

let shutdownPromise:Promise<void>|undefined;
function shutdown(signal:"SIGINT"|"SIGTERM"):Promise<void>{
  if(shutdownPromise)return shutdownPromise;
  shutdownPromise=(async()=>{
    readiness.markDraining();
    logger.info("server.draining",{signal,drainMs:config.shutdownDrainMs});
    await new Promise(resolve=>setTimeout(resolve,config.shutdownDrainMs));
    let timedOut=false;
    await new Promise<void>(resolve=>{const timer=setTimeout(()=>{timedOut=true;server.closeAllConnections();resolve()},config.shutdownTimeoutMs-config.shutdownDrainMs);server.close(()=>{clearTimeout(timer);resolve()})});
    await pool.end();
    logger.info("server.stopped",{signal,timedOut});
  })();
  return shutdownPromise;
}

process.once("SIGINT",()=>void shutdown("SIGINT"));
process.once("SIGTERM",()=>void shutdown("SIGTERM"));
