import{randomUUID}from"node:crypto";
import type pg from"pg";
export type FulfillmentJob=Readonly<{id:string;shipmentId:string;workspaceId:string;attempt:number}>;
export type FulfillmentContext=Readonly<{shopifyOrderId:string;carrier:string|null;trackingNumber:string|null;trackingUrl:string|null;items:readonly Readonly<{shopifyLineItemId:string;quantity:number}>[]}>;

export class ShopifyFulfillmentJobStore{
  constructor(private readonly pool:pg.Pool){}
  async claim(worker:string,lease=60,max=8):Promise<FulfillmentJob|null>{const q=await this.pool.query<{id:string;shipment_id:string;workspace_id:string;attempts:number}>(`WITH n AS(SELECT j.id,o.workspace_id FROM shopify_fulfillment_jobs j JOIN fulfillment_shipments s ON s.id=j.shipment_id JOIN commerce_orders o ON o.id=s.commerce_order_id WHERE(j.status='PENDING' AND j.available_at<=now() AND j.attempts<$3)OR(j.status='RUNNING' AND j.lease_expires_at<=now() AND j.attempts<=$3)ORDER BY j.available_at,j.created_at FOR UPDATE OF j SKIP LOCKED LIMIT 1)UPDATE shopify_fulfillment_jobs j SET status='RUNNING',attempts=attempts+1,locked_by=$1,lease_expires_at=now()+make_interval(secs=>$2) FROM n WHERE j.id=n.id RETURNING j.id,j.shipment_id,n.workspace_id,j.attempts`,[worker,lease,max]);const r=q.rows[0];return r?{id:r.id,shipmentId:r.shipment_id,workspaceId:r.workspace_id,attempt:r.attempts}:null}
  async extendLease(id:string,worker:string,lease=60):Promise<boolean>{const q=await this.pool.query(`UPDATE shopify_fulfillment_jobs SET lease_expires_at=now()+make_interval(secs=>$3) WHERE id=$1 AND status='RUNNING' AND locked_by=$2 AND lease_expires_at>now()`,[id,worker,lease]);return q.rowCount===1}
  async context(job:FulfillmentJob):Promise<FulfillmentContext>{const q=await this.pool.query<{shopify_order_id:string;carrier:string|null;tracking_number:string|null;tracking_url:string|null}>(`SELECT o.shopify_order_id,s.carrier,s.tracking_number,s.tracking_url FROM fulfillment_shipments s JOIN commerce_orders o ON o.id=s.commerce_order_id WHERE s.id=$1`,[job.shipmentId]);if(!q.rows[0])throw new Error('Shipment context not found');const items=await this.pool.query<{shopify_line_item_id:string;quantity:number}>(`SELECT shopify_line_item_id,quantity FROM fulfillment_shipment_items WHERE shipment_id=$1`,[job.shipmentId]);if(!items.rowCount)throw Object.assign(new Error('Shipment contains no mapped items'),{status:422});return{shopifyOrderId:q.rows[0].shopify_order_id,carrier:q.rows[0].carrier,trackingNumber:q.rows[0].tracking_number,trackingUrl:q.rows[0].tracking_url,items:items.rows.map(x=>({shopifyLineItemId:x.shopify_line_item_id,quantity:x.quantity}))}}
  async success(job:FulfillmentJob,worker:string,result:{fulfillmentId:string;payload:unknown;raw:unknown}):Promise<boolean>{const client=await this.pool.connect();try{await client.query('BEGIN');const owned=await client.query(`UPDATE shopify_fulfillment_jobs SET status='SUCCEEDED',shopify_fulfillment_id=$3,request_payload=$4::jsonb,response_payload=$5::jsonb,finished_at=now(),locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND status='RUNNING' AND locked_by=$2 AND lease_expires_at>now() RETURNING id`,[job.id,worker,result.fulfillmentId,JSON.stringify(result.payload),JSON.stringify(result.raw)]);if(owned.rowCount!==1){await client.query('ROLLBACK');return false}const recovered=Boolean(result.payload&&typeof result.payload==='object'&&'recovered'in result.payload&&(result.payload as{recovered?:unknown}).recovered===true);await client.query(`INSERT INTO shopify_fulfillment_job_events(id,workspace_id,shipment_id,shopify_fulfillment_job_id,event_type,actor_id,shopify_fulfillment_id)VALUES($1,$2,$3,$4,$5,$6,$7)`,[randomUUID(),job.workspaceId,job.shipmentId,job.id,recovered?'RECOVERED':'CREATED',worker,result.fulfillmentId]);await client.query('COMMIT');return true}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
  async retry(job:FulfillmentJob,worker:string,delay:number,error:string){await this.pool.query(`UPDATE shopify_fulfillment_jobs SET status='PENDING',available_at=now()+make_interval(secs=>$3/1000.0),last_error=$4,locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND status='RUNNING' AND locked_by=$2 AND lease_expires_at>now()`,[job.id,worker,delay,error])}
  async deferConnection(job:FulfillmentJob,worker:string,delay=30_000){await this.pool.query(`UPDATE shopify_fulfillment_jobs SET status='PENDING',attempts=GREATEST(0,attempts-1),available_at=now()+make_interval(secs=>$3/1000.0),last_error='WAITING_FOR_SHOPIFY_CONNECTION',locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND status='RUNNING' AND locked_by=$2 AND lease_expires_at>now()`,[job.id,worker,delay])}
  async deferRateLimit(job:FulfillmentJob,worker:string,delay:number){await this.pool.query(`UPDATE shopify_fulfillment_jobs SET status='PENDING',attempts=GREATEST(0,attempts-1),available_at=now()+make_interval(secs=>$3/1000.0),last_error='WAITING_FOR_SHOPIFY_RATE_LIMIT',locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND status='RUNNING' AND locked_by=$2 AND lease_expires_at>now()`,[job.id,worker,delay])}
  async fail(job:FulfillmentJob,worker:string,error:string):Promise<boolean>{const client=await this.pool.connect();try{await client.query('BEGIN');const owned=await client.query(`UPDATE shopify_fulfillment_jobs SET status='FAILED',last_error=$3,finished_at=now(),locked_by=NULL,lease_expires_at=NULL WHERE id=$1 AND status='RUNNING' AND locked_by=$2 AND lease_expires_at>now() RETURNING id`,[job.id,worker,error]);if(owned.rowCount!==1){await client.query('ROLLBACK');return false}await client.query(`INSERT INTO shopify_fulfillment_job_events(id,workspace_id,shipment_id,shopify_fulfillment_job_id,event_type,actor_id,shopify_fulfillment_id,detail)VALUES($1,$2,$3,$4,'FAILED',$5,NULL,$6)`,[randomUUID(),job.workspaceId,job.shipmentId,job.id,worker,error]);await client.query('COMMIT');return true}catch(cause){await client.query('ROLLBACK');throw cause}finally{client.release()}}
}
